// Code generated by ent, DO NOT EDIT.

package sharedaccountusageledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sharedaccountusageledger type in the database.
	Label = "shared_account_usage_ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldListingID holds the string denoting the listing_id field in the database.
	FieldListingID = "listing_id"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldConsumerUserID holds the string denoting the consumer_user_id field in the database.
	FieldConsumerUserID = "consumer_user_id"
	// FieldGrossCost holds the string denoting the gross_cost field in the database.
	FieldGrossCost = "gross_cost"
	// FieldFeeRatePercent holds the string denoting the fee_rate_percent field in the database.
	FieldFeeRatePercent = "fee_rate_percent"
	// FieldPlatformFee holds the string denoting the platform_fee field in the database.
	FieldPlatformFee = "platform_fee"
	// FieldOwnerAmount holds the string denoting the owner_amount field in the database.
	FieldOwnerAmount = "owner_amount"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldFrozenUntil holds the string denoting the frozen_until field in the database.
	FieldFrozenUntil = "frozen_until"
	// FieldReleasedAt holds the string denoting the released_at field in the database.
	FieldReleasedAt = "released_at"
	// Table holds the table name of the sharedaccountusageledger in the database.
	Table = "shared_account_usage_ledger"
)

// Columns holds all SQL columns for sharedaccountusageledger fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRequestID,
	FieldUsageLogID,
	FieldListingID,
	FieldOwnerUserID,
	FieldConsumerUserID,
	FieldGrossCost,
	FieldFeeRatePercent,
	FieldPlatformFee,
	FieldOwnerAmount,
	FieldAction,
	FieldFrozenUntil,
	FieldReleasedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultAction holds the default value on creation for the "action" field.
	DefaultAction string
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
)

// OrderOption defines the ordering options for the SharedAccountUsageLedger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByListingID orders the results by the listing_id field.
func ByListingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldListingID, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByConsumerUserID orders the results by the consumer_user_id field.
func ByConsumerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumerUserID, opts...).ToFunc()
}

// ByGrossCost orders the results by the gross_cost field.
func ByGrossCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrossCost, opts...).ToFunc()
}

// ByFeeRatePercent orders the results by the fee_rate_percent field.
func ByFeeRatePercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeRatePercent, opts...).ToFunc()
}

// ByPlatformFee orders the results by the platform_fee field.
func ByPlatformFee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformFee, opts...).ToFunc()
}

// ByOwnerAmount orders the results by the owner_amount field.
func ByOwnerAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerAmount, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByFrozenUntil orders the results by the frozen_until field.
func ByFrozenUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozenUntil, opts...).ToFunc()
}

// ByReleasedAt orders the results by the released_at field.
func ByReleasedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleasedAt, opts...).ToFunc()
}
