// Code generated by ent, DO NOT EDIT.

package sharedaccountusageledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldRequestID, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldUsageLogID, v))
}

// ListingID applies equality check predicate on the "listing_id" field. It's identical to ListingIDEQ.
func ListingID(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldListingID, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldOwnerUserID, v))
}

// ConsumerUserID applies equality check predicate on the "consumer_user_id" field. It's identical to ConsumerUserIDEQ.
func ConsumerUserID(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldConsumerUserID, v))
}

// GrossCost applies equality check predicate on the "gross_cost" field. It's identical to GrossCostEQ.
func GrossCost(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldGrossCost, v))
}

// FeeRatePercent applies equality check predicate on the "fee_rate_percent" field. It's identical to FeeRatePercentEQ.
func FeeRatePercent(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldFeeRatePercent, v))
}

// PlatformFee applies equality check predicate on the "platform_fee" field. It's identical to PlatformFeeEQ.
func PlatformFee(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldPlatformFee, v))
}

// OwnerAmount applies equality check predicate on the "owner_amount" field. It's identical to OwnerAmountEQ.
func OwnerAmount(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldOwnerAmount, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldAction, v))
}

// FrozenUntil applies equality check predicate on the "frozen_until" field. It's identical to FrozenUntilEQ.
func FrozenUntil(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldFrozenUntil, v))
}

// ReleasedAt applies equality check predicate on the "released_at" field. It's identical to ReleasedAtEQ.
func ReleasedAt(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldReleasedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldUpdatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldContainsFold(FieldRequestID, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotNull(FieldUsageLogID))
}

// ListingIDEQ applies the EQ predicate on the "listing_id" field.
func ListingIDEQ(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldListingID, v))
}

// ListingIDNEQ applies the NEQ predicate on the "listing_id" field.
func ListingIDNEQ(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldListingID, v))
}

// ListingIDIn applies the In predicate on the "listing_id" field.
func ListingIDIn(vs ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldListingID, vs...))
}

// ListingIDNotIn applies the NotIn predicate on the "listing_id" field.
func ListingIDNotIn(vs ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldListingID, vs...))
}

// ListingIDGT applies the GT predicate on the "listing_id" field.
func ListingIDGT(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldListingID, v))
}

// ListingIDGTE applies the GTE predicate on the "listing_id" field.
func ListingIDGTE(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldListingID, v))
}

// ListingIDLT applies the LT predicate on the "listing_id" field.
func ListingIDLT(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldListingID, v))
}

// ListingIDLTE applies the LTE predicate on the "listing_id" field.
func ListingIDLTE(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldListingID, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldOwnerUserID, v))
}

// ConsumerUserIDEQ applies the EQ predicate on the "consumer_user_id" field.
func ConsumerUserIDEQ(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldConsumerUserID, v))
}

// ConsumerUserIDNEQ applies the NEQ predicate on the "consumer_user_id" field.
func ConsumerUserIDNEQ(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldConsumerUserID, v))
}

// ConsumerUserIDIn applies the In predicate on the "consumer_user_id" field.
func ConsumerUserIDIn(vs ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldConsumerUserID, vs...))
}

// ConsumerUserIDNotIn applies the NotIn predicate on the "consumer_user_id" field.
func ConsumerUserIDNotIn(vs ...int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldConsumerUserID, vs...))
}

// ConsumerUserIDGT applies the GT predicate on the "consumer_user_id" field.
func ConsumerUserIDGT(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldConsumerUserID, v))
}

// ConsumerUserIDGTE applies the GTE predicate on the "consumer_user_id" field.
func ConsumerUserIDGTE(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldConsumerUserID, v))
}

// ConsumerUserIDLT applies the LT predicate on the "consumer_user_id" field.
func ConsumerUserIDLT(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldConsumerUserID, v))
}

// ConsumerUserIDLTE applies the LTE predicate on the "consumer_user_id" field.
func ConsumerUserIDLTE(v int64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldConsumerUserID, v))
}

// GrossCostEQ applies the EQ predicate on the "gross_cost" field.
func GrossCostEQ(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldGrossCost, v))
}

// GrossCostNEQ applies the NEQ predicate on the "gross_cost" field.
func GrossCostNEQ(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldGrossCost, v))
}

// GrossCostIn applies the In predicate on the "gross_cost" field.
func GrossCostIn(vs ...float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldGrossCost, vs...))
}

// GrossCostNotIn applies the NotIn predicate on the "gross_cost" field.
func GrossCostNotIn(vs ...float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldGrossCost, vs...))
}

// GrossCostGT applies the GT predicate on the "gross_cost" field.
func GrossCostGT(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldGrossCost, v))
}

// GrossCostGTE applies the GTE predicate on the "gross_cost" field.
func GrossCostGTE(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldGrossCost, v))
}

// GrossCostLT applies the LT predicate on the "gross_cost" field.
func GrossCostLT(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldGrossCost, v))
}

// GrossCostLTE applies the LTE predicate on the "gross_cost" field.
func GrossCostLTE(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldGrossCost, v))
}

// FeeRatePercentEQ applies the EQ predicate on the "fee_rate_percent" field.
func FeeRatePercentEQ(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldFeeRatePercent, v))
}

// FeeRatePercentNEQ applies the NEQ predicate on the "fee_rate_percent" field.
func FeeRatePercentNEQ(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldFeeRatePercent, v))
}

// FeeRatePercentIn applies the In predicate on the "fee_rate_percent" field.
func FeeRatePercentIn(vs ...float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldFeeRatePercent, vs...))
}

// FeeRatePercentNotIn applies the NotIn predicate on the "fee_rate_percent" field.
func FeeRatePercentNotIn(vs ...float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldFeeRatePercent, vs...))
}

// FeeRatePercentGT applies the GT predicate on the "fee_rate_percent" field.
func FeeRatePercentGT(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldFeeRatePercent, v))
}

// FeeRatePercentGTE applies the GTE predicate on the "fee_rate_percent" field.
func FeeRatePercentGTE(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldFeeRatePercent, v))
}

// FeeRatePercentLT applies the LT predicate on the "fee_rate_percent" field.
func FeeRatePercentLT(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldFeeRatePercent, v))
}

// FeeRatePercentLTE applies the LTE predicate on the "fee_rate_percent" field.
func FeeRatePercentLTE(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldFeeRatePercent, v))
}

// PlatformFeeEQ applies the EQ predicate on the "platform_fee" field.
func PlatformFeeEQ(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldPlatformFee, v))
}

// PlatformFeeNEQ applies the NEQ predicate on the "platform_fee" field.
func PlatformFeeNEQ(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldPlatformFee, v))
}

// PlatformFeeIn applies the In predicate on the "platform_fee" field.
func PlatformFeeIn(vs ...float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldPlatformFee, vs...))
}

// PlatformFeeNotIn applies the NotIn predicate on the "platform_fee" field.
func PlatformFeeNotIn(vs ...float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldPlatformFee, vs...))
}

// PlatformFeeGT applies the GT predicate on the "platform_fee" field.
func PlatformFeeGT(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldPlatformFee, v))
}

// PlatformFeeGTE applies the GTE predicate on the "platform_fee" field.
func PlatformFeeGTE(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldPlatformFee, v))
}

// PlatformFeeLT applies the LT predicate on the "platform_fee" field.
func PlatformFeeLT(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldPlatformFee, v))
}

// PlatformFeeLTE applies the LTE predicate on the "platform_fee" field.
func PlatformFeeLTE(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldPlatformFee, v))
}

// OwnerAmountEQ applies the EQ predicate on the "owner_amount" field.
func OwnerAmountEQ(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldOwnerAmount, v))
}

// OwnerAmountNEQ applies the NEQ predicate on the "owner_amount" field.
func OwnerAmountNEQ(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldOwnerAmount, v))
}

// OwnerAmountIn applies the In predicate on the "owner_amount" field.
func OwnerAmountIn(vs ...float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldOwnerAmount, vs...))
}

// OwnerAmountNotIn applies the NotIn predicate on the "owner_amount" field.
func OwnerAmountNotIn(vs ...float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldOwnerAmount, vs...))
}

// OwnerAmountGT applies the GT predicate on the "owner_amount" field.
func OwnerAmountGT(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldOwnerAmount, v))
}

// OwnerAmountGTE applies the GTE predicate on the "owner_amount" field.
func OwnerAmountGTE(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldOwnerAmount, v))
}

// OwnerAmountLT applies the LT predicate on the "owner_amount" field.
func OwnerAmountLT(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldOwnerAmount, v))
}

// OwnerAmountLTE applies the LTE predicate on the "owner_amount" field.
func OwnerAmountLTE(v float64) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldOwnerAmount, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldContainsFold(FieldAction, v))
}

// FrozenUntilEQ applies the EQ predicate on the "frozen_until" field.
func FrozenUntilEQ(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldFrozenUntil, v))
}

// FrozenUntilNEQ applies the NEQ predicate on the "frozen_until" field.
func FrozenUntilNEQ(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldFrozenUntil, v))
}

// FrozenUntilIn applies the In predicate on the "frozen_until" field.
func FrozenUntilIn(vs ...time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldFrozenUntil, vs...))
}

// FrozenUntilNotIn applies the NotIn predicate on the "frozen_until" field.
func FrozenUntilNotIn(vs ...time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldFrozenUntil, vs...))
}

// FrozenUntilGT applies the GT predicate on the "frozen_until" field.
func FrozenUntilGT(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldFrozenUntil, v))
}

// FrozenUntilGTE applies the GTE predicate on the "frozen_until" field.
func FrozenUntilGTE(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldFrozenUntil, v))
}

// FrozenUntilLT applies the LT predicate on the "frozen_until" field.
func FrozenUntilLT(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldFrozenUntil, v))
}

// FrozenUntilLTE applies the LTE predicate on the "frozen_until" field.
func FrozenUntilLTE(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldFrozenUntil, v))
}

// FrozenUntilIsNil applies the IsNil predicate on the "frozen_until" field.
func FrozenUntilIsNil() predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIsNull(FieldFrozenUntil))
}

// FrozenUntilNotNil applies the NotNil predicate on the "frozen_until" field.
func FrozenUntilNotNil() predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotNull(FieldFrozenUntil))
}

// ReleasedAtEQ applies the EQ predicate on the "released_at" field.
func ReleasedAtEQ(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldEQ(FieldReleasedAt, v))
}

// ReleasedAtNEQ applies the NEQ predicate on the "released_at" field.
func ReleasedAtNEQ(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNEQ(FieldReleasedAt, v))
}

// ReleasedAtIn applies the In predicate on the "released_at" field.
func ReleasedAtIn(vs ...time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIn(FieldReleasedAt, vs...))
}

// ReleasedAtNotIn applies the NotIn predicate on the "released_at" field.
func ReleasedAtNotIn(vs ...time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotIn(FieldReleasedAt, vs...))
}

// ReleasedAtGT applies the GT predicate on the "released_at" field.
func ReleasedAtGT(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGT(FieldReleasedAt, v))
}

// ReleasedAtGTE applies the GTE predicate on the "released_at" field.
func ReleasedAtGTE(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldGTE(FieldReleasedAt, v))
}

// ReleasedAtLT applies the LT predicate on the "released_at" field.
func ReleasedAtLT(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLT(FieldReleasedAt, v))
}

// ReleasedAtLTE applies the LTE predicate on the "released_at" field.
func ReleasedAtLTE(v time.Time) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldLTE(FieldReleasedAt, v))
}

// ReleasedAtIsNil applies the IsNil predicate on the "released_at" field.
func ReleasedAtIsNil() predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldIsNull(FieldReleasedAt))
}

// ReleasedAtNotNil applies the NotNil predicate on the "released_at" field.
func ReleasedAtNotNil() predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.FieldNotNull(FieldReleasedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharedAccountUsageLedger) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharedAccountUsageLedger) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharedAccountUsageLedger) predicate.SharedAccountUsageLedger {
	return predicate.SharedAccountUsageLedger(sql.NotPredicates(p))
}
