// Code generated by ent, DO NOT EDIT.

package accountproxy

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldEQ(FieldAccountID, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldEQ(FieldProxyID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldEQ(FieldPosition, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldLTE(FieldAccountID, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDGT applies the GT predicate on the "proxy_id" field.
func ProxyIDGT(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldGT(FieldProxyID, v))
}

// ProxyIDGTE applies the GTE predicate on the "proxy_id" field.
func ProxyIDGTE(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldGTE(FieldProxyID, v))
}

// ProxyIDLT applies the LT predicate on the "proxy_id" field.
func ProxyIDLT(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldLT(FieldProxyID, v))
}

// ProxyIDLTE applies the LTE predicate on the "proxy_id" field.
func ProxyIDLTE(v int64) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldLTE(FieldProxyID, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.AccountProxy {
	return predicate.AccountProxy(sql.FieldLTE(FieldPosition, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountProxy) predicate.AccountProxy {
	return predicate.AccountProxy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountProxy) predicate.AccountProxy {
	return predicate.AccountProxy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountProxy) predicate.AccountProxy {
	return predicate.AccountProxy(sql.NotPredicates(p))
}
