// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountproxy"
)

// AccountProxy is the model entity for the AccountProxy schema.
type AccountProxy struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID int64 `json:"proxy_id,omitempty"`
	// Position holds the value of the "position" field.
	Position     int `json:"position,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountProxy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountproxy.FieldID, accountproxy.FieldAccountID, accountproxy.FieldProxyID, accountproxy.FieldPosition:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountProxy fields.
func (_m *AccountProxy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountproxy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountproxy.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountproxy.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = value.Int64
			}
		case accountproxy.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountProxy.
// This includes values selected through modifiers, order, etc.
func (_m *AccountProxy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountProxy.
// Note that you need to call AccountProxy.Unwrap() before calling this method if this AccountProxy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountProxy) Update() *AccountProxyUpdateOne {
	return NewAccountProxyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountProxy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountProxy) Unwrap() *AccountProxy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountProxy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountProxy) String() string {
	var builder strings.Builder
	builder.WriteString("AccountProxy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("proxy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProxyID))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteByte(')')
	return builder.String()
}

// AccountProxies is a parsable slice of AccountProxy.
type AccountProxies []*AccountProxy
