// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountproxy"
)

// AccountProxyCreate is the builder for creating a AccountProxy entity.
type AccountProxyCreate struct {
	config
	mutation *AccountProxyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountProxyCreate) SetAccountID(v int64) *AccountProxyCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *AccountProxyCreate) SetProxyID(v int64) *AccountProxyCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *AccountProxyCreate) SetPosition(v int) *AccountProxyCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *AccountProxyCreate) SetNillablePosition(v *int) *AccountProxyCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// Mutation returns the AccountProxyMutation object of the builder.
func (_c *AccountProxyCreate) Mutation() *AccountProxyMutation {
	return _c.mutation
}

// Save creates the AccountProxy in the database.
func (_c *AccountProxyCreate) Save(ctx context.Context) (*AccountProxy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountProxyCreate) SaveX(ctx context.Context) *AccountProxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountProxyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountProxyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountProxyCreate) defaults() {
	if _, ok := _c.mutation.Position(); !ok {
		v := accountproxy.DefaultPosition
		_c.mutation.SetPosition(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountProxyCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountProxy.account_id"`)}
	}
	if _, ok := _c.mutation.ProxyID(); !ok {
		return &ValidationError{Name: "proxy_id", err: errors.New(`ent: missing required field "AccountProxy.proxy_id"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "AccountProxy.position"`)}
	}
	return nil
}

func (_c *AccountProxyCreate) sqlSave(ctx context.Context) (*AccountProxy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountProxyCreate) createSpec() (*AccountProxy, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountProxy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountproxy.Table, sqlgraph.NewFieldSpec(accountproxy.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountproxy.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.ProxyID(); ok {
		_spec.SetField(accountproxy.FieldProxyID, field.TypeInt64, value)
		_node.ProxyID = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(accountproxy.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountProxy.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountProxyUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountProxyCreate) OnConflict(opts ...sql.ConflictOption) *AccountProxyUpsertOne {
	_c.conflict = opts
	return &AccountProxyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountProxyCreate) OnConflictColumns(columns ...string) *AccountProxyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountProxyUpsertOne{
		create: _c,
	}
}

type (
	// AccountProxyUpsertOne is the builder for "upsert"-ing
	//  one AccountProxy node.
	AccountProxyUpsertOne struct {
		create *AccountProxyCreate
	}

	// AccountProxyUpsert is the "OnConflict" setter.
	AccountProxyUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountProxyUpsert) SetAccountID(v int64) *AccountProxyUpsert {
	u.Set(accountproxy.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountProxyUpsert) UpdateAccountID() *AccountProxyUpsert {
	u.SetExcluded(accountproxy.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountProxyUpsert) AddAccountID(v int64) *AccountProxyUpsert {
	u.Add(accountproxy.FieldAccountID, v)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountProxyUpsert) SetProxyID(v int64) *AccountProxyUpsert {
	u.Set(accountproxy.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountProxyUpsert) UpdateProxyID() *AccountProxyUpsert {
	u.SetExcluded(accountproxy.FieldProxyID)
	return u
}

// AddProxyID adds v to the "proxy_id" field.
func (u *AccountProxyUpsert) AddProxyID(v int64) *AccountProxyUpsert {
	u.Add(accountproxy.FieldProxyID, v)
	return u
}

// SetPosition sets the "position" field.
func (u *AccountProxyUpsert) SetPosition(v int) *AccountProxyUpsert {
	u.Set(accountproxy.FieldPosition, v)
	return u
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *AccountProxyUpsert) UpdatePosition() *AccountProxyUpsert {
	u.SetExcluded(accountproxy.FieldPosition)
	return u
}

// AddPosition adds v to the "position" field.
func (u *AccountProxyUpsert) AddPosition(v int) *AccountProxyUpsert {
	u.Add(accountproxy.FieldPosition, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountProxyUpsertOne) UpdateNewValues() *AccountProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountProxyUpsertOne) Ignore() *AccountProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountProxyUpsertOne) DoNothing() *AccountProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountProxyCreate.OnConflict
// documentation for more info.
func (u *AccountProxyUpsertOne) Update(set func(*AccountProxyUpsert)) *AccountProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountProxyUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountProxyUpsertOne) SetAccountID(v int64) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountProxyUpsertOne) AddAccountID(v int64) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountProxyUpsertOne) UpdateAccountID() *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateAccountID()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountProxyUpsertOne) SetProxyID(v int64) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetProxyID(v)
	})
}

// AddProxyID adds v to the "proxy_id" field.
func (u *AccountProxyUpsertOne) AddProxyID(v int64) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountProxyUpsertOne) UpdateProxyID() *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateProxyID()
	})
}

// SetPosition sets the "position" field.
func (u *AccountProxyUpsertOne) SetPosition(v int) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *AccountProxyUpsertOne) AddPosition(v int) *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *AccountProxyUpsertOne) UpdatePosition() *AccountProxyUpsertOne {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdatePosition()
	})
}

// Exec executes the query.
func (u *AccountProxyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountProxyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountProxyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountProxyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountProxyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountProxyCreateBulk is the builder for creating many AccountProxy entities in bulk.
type AccountProxyCreateBulk struct {
	config
	err      error
	builders []*AccountProxyCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountProxy entities in the database.
func (_c *AccountProxyCreateBulk) Save(ctx context.Context) ([]*AccountProxy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountProxy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountProxyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountProxyCreateBulk) SaveX(ctx context.Context) []*AccountProxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountProxyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountProxyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountProxy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountProxyUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountProxyCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountProxyUpsertBulk {
	_c.conflict = opts
	return &AccountProxyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountProxyCreateBulk) OnConflictColumns(columns ...string) *AccountProxyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountProxyUpsertBulk{
		create: _c,
	}
}

// AccountProxyUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountProxy nodes.
type AccountProxyUpsertBulk struct {
	create *AccountProxyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountProxyUpsertBulk) UpdateNewValues() *AccountProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountProxy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountProxyUpsertBulk) Ignore() *AccountProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountProxyUpsertBulk) DoNothing() *AccountProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountProxyCreateBulk.OnConflict
// documentation for more info.
func (u *AccountProxyUpsertBulk) Update(set func(*AccountProxyUpsert)) *AccountProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountProxyUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountProxyUpsertBulk) SetAccountID(v int64) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountProxyUpsertBulk) AddAccountID(v int64) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountProxyUpsertBulk) UpdateAccountID() *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateAccountID()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountProxyUpsertBulk) SetProxyID(v int64) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetProxyID(v)
	})
}

// AddProxyID adds v to the "proxy_id" field.
func (u *AccountProxyUpsertBulk) AddProxyID(v int64) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountProxyUpsertBulk) UpdateProxyID() *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdateProxyID()
	})
}

// SetPosition sets the "position" field.
func (u *AccountProxyUpsertBulk) SetPosition(v int) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *AccountProxyUpsertBulk) AddPosition(v int) *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *AccountProxyUpsertBulk) UpdatePosition() *AccountProxyUpsertBulk {
	return u.Update(func(s *AccountProxyUpsert) {
		s.UpdatePosition()
	})
}

// Exec executes the query.
func (u *AccountProxyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountProxyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountProxyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountProxyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
