// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountusageledger"
)

// SharedAccountUsageLedger is the model entity for the SharedAccountUsageLedger schema.
type SharedAccountUsageLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// ListingID holds the value of the "listing_id" field.
	ListingID int64 `json:"listing_id,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// ConsumerUserID holds the value of the "consumer_user_id" field.
	ConsumerUserID int64 `json:"consumer_user_id,omitempty"`
	// GrossCost holds the value of the "gross_cost" field.
	GrossCost float64 `json:"gross_cost,omitempty"`
	// FeeRatePercent holds the value of the "fee_rate_percent" field.
	FeeRatePercent float64 `json:"fee_rate_percent,omitempty"`
	// PlatformFee holds the value of the "platform_fee" field.
	PlatformFee float64 `json:"platform_fee,omitempty"`
	// OwnerAmount holds the value of the "owner_amount" field.
	OwnerAmount float64 `json:"owner_amount,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// FrozenUntil holds the value of the "frozen_until" field.
	FrozenUntil *time.Time `json:"frozen_until,omitempty"`
	// ReleasedAt holds the value of the "released_at" field.
	ReleasedAt   *time.Time `json:"released_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SharedAccountUsageLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sharedaccountusageledger.FieldGrossCost, sharedaccountusageledger.FieldFeeRatePercent, sharedaccountusageledger.FieldPlatformFee, sharedaccountusageledger.FieldOwnerAmount:
			values[i] = new(sql.NullFloat64)
		case sharedaccountusageledger.FieldID, sharedaccountusageledger.FieldUsageLogID, sharedaccountusageledger.FieldListingID, sharedaccountusageledger.FieldOwnerUserID, sharedaccountusageledger.FieldConsumerUserID:
			values[i] = new(sql.NullInt64)
		case sharedaccountusageledger.FieldRequestID, sharedaccountusageledger.FieldAction:
			values[i] = new(sql.NullString)
		case sharedaccountusageledger.FieldCreatedAt, sharedaccountusageledger.FieldUpdatedAt, sharedaccountusageledger.FieldFrozenUntil, sharedaccountusageledger.FieldReleasedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SharedAccountUsageLedger fields.
func (_m *SharedAccountUsageLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sharedaccountusageledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sharedaccountusageledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sharedaccountusageledger.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sharedaccountusageledger.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case sharedaccountusageledger.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case sharedaccountusageledger.FieldListingID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field listing_id", values[i])
			} else if value.Valid {
				_m.ListingID = value.Int64
			}
		case sharedaccountusageledger.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case sharedaccountusageledger.FieldConsumerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_user_id", values[i])
			} else if value.Valid {
				_m.ConsumerUserID = value.Int64
			}
		case sharedaccountusageledger.FieldGrossCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gross_cost", values[i])
			} else if value.Valid {
				_m.GrossCost = value.Float64
			}
		case sharedaccountusageledger.FieldFeeRatePercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_rate_percent", values[i])
			} else if value.Valid {
				_m.FeeRatePercent = value.Float64
			}
		case sharedaccountusageledger.FieldPlatformFee:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field platform_fee", values[i])
			} else if value.Valid {
				_m.PlatformFee = value.Float64
			}
		case sharedaccountusageledger.FieldOwnerAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_amount", values[i])
			} else if value.Valid {
				_m.OwnerAmount = value.Float64
			}
		case sharedaccountusageledger.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case sharedaccountusageledger.FieldFrozenUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_until", values[i])
			} else if value.Valid {
				_m.FrozenUntil = new(time.Time)
				*_m.FrozenUntil = value.Time
			}
		case sharedaccountusageledger.FieldReleasedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field released_at", values[i])
			} else if value.Valid {
				_m.ReleasedAt = new(time.Time)
				*_m.ReleasedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SharedAccountUsageLedger.
// This includes values selected through modifiers, order, etc.
func (_m *SharedAccountUsageLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SharedAccountUsageLedger.
// Note that you need to call SharedAccountUsageLedger.Unwrap() before calling this method if this SharedAccountUsageLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SharedAccountUsageLedger) Update() *SharedAccountUsageLedgerUpdateOne {
	return NewSharedAccountUsageLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SharedAccountUsageLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SharedAccountUsageLedger) Unwrap() *SharedAccountUsageLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SharedAccountUsageLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SharedAccountUsageLedger) String() string {
	var builder strings.Builder
	builder.WriteString("SharedAccountUsageLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("listing_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ListingID))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("consumer_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsumerUserID))
	builder.WriteString(", ")
	builder.WriteString("gross_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrossCost))
	builder.WriteString(", ")
	builder.WriteString("fee_rate_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeRatePercent))
	builder.WriteString(", ")
	builder.WriteString("platform_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlatformFee))
	builder.WriteString(", ")
	builder.WriteString("owner_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerAmount))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	if v := _m.FrozenUntil; v != nil {
		builder.WriteString("frozen_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReleasedAt; v != nil {
		builder.WriteString("released_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SharedAccountUsageLedgers is a parsable slice of SharedAccountUsageLedger.
type SharedAccountUsageLedgers []*SharedAccountUsageLedger
