// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountlisting"
)

// SharedAccountListing is the model entity for the SharedAccountListing schema.
type SharedAccountListing struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ProxyConfigEncrypted holds the value of the "proxy_config_encrypted" field.
	ProxyConfigEncrypted *string `json:"proxy_config_encrypted,omitempty"`
	// ConcurrencyLimit holds the value of the "concurrency_limit" field.
	ConcurrencyLimit int `json:"concurrency_limit,omitempty"`
	// ConcurrencyMultiplier holds the value of the "concurrency_multiplier" field.
	ConcurrencyMultiplier float64 `json:"concurrency_multiplier,omitempty"`
	// SellRate holds the value of the "sell_rate" field.
	SellRate float64 `json:"sell_rate,omitempty"`
	// FeeRateOverride holds the value of the "fee_rate_override" field.
	FeeRateOverride *float64 `json:"fee_rate_override,omitempty"`
	// TotalCallCount holds the value of the "total_call_count" field.
	TotalCallCount int64 `json:"total_call_count,omitempty"`
	// LastCalledAt holds the value of the "last_called_at" field.
	LastCalledAt *time.Time `json:"last_called_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SharedAccountListing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sharedaccountlisting.FieldConcurrencyMultiplier, sharedaccountlisting.FieldSellRate, sharedaccountlisting.FieldFeeRateOverride:
			values[i] = new(sql.NullFloat64)
		case sharedaccountlisting.FieldID, sharedaccountlisting.FieldOwnerUserID, sharedaccountlisting.FieldAccountID, sharedaccountlisting.FieldConcurrencyLimit, sharedaccountlisting.FieldTotalCallCount:
			values[i] = new(sql.NullInt64)
		case sharedaccountlisting.FieldPlatform, sharedaccountlisting.FieldDisplayName, sharedaccountlisting.FieldStatus, sharedaccountlisting.FieldProxyConfigEncrypted:
			values[i] = new(sql.NullString)
		case sharedaccountlisting.FieldCreatedAt, sharedaccountlisting.FieldUpdatedAt, sharedaccountlisting.FieldDeletedAt, sharedaccountlisting.FieldLastCalledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SharedAccountListing fields.
func (_m *SharedAccountListing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sharedaccountlisting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sharedaccountlisting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sharedaccountlisting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sharedaccountlisting.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case sharedaccountlisting.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case sharedaccountlisting.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case sharedaccountlisting.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case sharedaccountlisting.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case sharedaccountlisting.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case sharedaccountlisting.FieldProxyConfigEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_config_encrypted", values[i])
			} else if value.Valid {
				_m.ProxyConfigEncrypted = new(string)
				*_m.ProxyConfigEncrypted = value.String
			}
		case sharedaccountlisting.FieldConcurrencyLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency_limit", values[i])
			} else if value.Valid {
				_m.ConcurrencyLimit = int(value.Int64)
			}
		case sharedaccountlisting.FieldConcurrencyMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency_multiplier", values[i])
			} else if value.Valid {
				_m.ConcurrencyMultiplier = value.Float64
			}
		case sharedaccountlisting.FieldSellRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sell_rate", values[i])
			} else if value.Valid {
				_m.SellRate = value.Float64
			}
		case sharedaccountlisting.FieldFeeRateOverride:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_rate_override", values[i])
			} else if value.Valid {
				_m.FeeRateOverride = new(float64)
				*_m.FeeRateOverride = value.Float64
			}
		case sharedaccountlisting.FieldTotalCallCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_call_count", values[i])
			} else if value.Valid {
				_m.TotalCallCount = value.Int64
			}
		case sharedaccountlisting.FieldLastCalledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_called_at", values[i])
			} else if value.Valid {
				_m.LastCalledAt = new(time.Time)
				*_m.LastCalledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SharedAccountListing.
// This includes values selected through modifiers, order, etc.
func (_m *SharedAccountListing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SharedAccountListing.
// Note that you need to call SharedAccountListing.Unwrap() before calling this method if this SharedAccountListing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SharedAccountListing) Update() *SharedAccountListingUpdateOne {
	return NewSharedAccountListingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SharedAccountListing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SharedAccountListing) Unwrap() *SharedAccountListing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SharedAccountListing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SharedAccountListing) String() string {
	var builder strings.Builder
	builder.WriteString("SharedAccountListing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ProxyConfigEncrypted; v != nil {
		builder.WriteString("proxy_config_encrypted=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("concurrency_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConcurrencyLimit))
	builder.WriteString(", ")
	builder.WriteString("concurrency_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConcurrencyMultiplier))
	builder.WriteString(", ")
	builder.WriteString("sell_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.SellRate))
	builder.WriteString(", ")
	if v := _m.FeeRateOverride; v != nil {
		builder.WriteString("fee_rate_override=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("total_call_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCallCount))
	builder.WriteString(", ")
	if v := _m.LastCalledAt; v != nil {
		builder.WriteString("last_called_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SharedAccountListings is a parsable slice of SharedAccountListing.
type SharedAccountListings []*SharedAccountListing
