// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountlisting"
)

// SharedAccountListingCreate is the builder for creating a SharedAccountListing entity.
type SharedAccountListingCreate struct {
	config
	mutation *SharedAccountListingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SharedAccountListingCreate) SetCreatedAt(v time.Time) *SharedAccountListingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableCreatedAt(v *time.Time) *SharedAccountListingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SharedAccountListingCreate) SetUpdatedAt(v time.Time) *SharedAccountListingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableUpdatedAt(v *time.Time) *SharedAccountListingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SharedAccountListingCreate) SetDeletedAt(v time.Time) *SharedAccountListingCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableDeletedAt(v *time.Time) *SharedAccountListingCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *SharedAccountListingCreate) SetOwnerUserID(v int64) *SharedAccountListingCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *SharedAccountListingCreate) SetAccountID(v int64) *SharedAccountListingCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *SharedAccountListingCreate) SetPlatform(v string) *SharedAccountListingCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *SharedAccountListingCreate) SetDisplayName(v string) *SharedAccountListingCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SharedAccountListingCreate) SetStatus(v string) *SharedAccountListingCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableStatus(v *string) *SharedAccountListingCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProxyConfigEncrypted sets the "proxy_config_encrypted" field.
func (_c *SharedAccountListingCreate) SetProxyConfigEncrypted(v string) *SharedAccountListingCreate {
	_c.mutation.SetProxyConfigEncrypted(v)
	return _c
}

// SetNillableProxyConfigEncrypted sets the "proxy_config_encrypted" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableProxyConfigEncrypted(v *string) *SharedAccountListingCreate {
	if v != nil {
		_c.SetProxyConfigEncrypted(*v)
	}
	return _c
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (_c *SharedAccountListingCreate) SetConcurrencyLimit(v int) *SharedAccountListingCreate {
	_c.mutation.SetConcurrencyLimit(v)
	return _c
}

// SetNillableConcurrencyLimit sets the "concurrency_limit" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableConcurrencyLimit(v *int) *SharedAccountListingCreate {
	if v != nil {
		_c.SetConcurrencyLimit(*v)
	}
	return _c
}

// SetConcurrencyMultiplier sets the "concurrency_multiplier" field.
func (_c *SharedAccountListingCreate) SetConcurrencyMultiplier(v float64) *SharedAccountListingCreate {
	_c.mutation.SetConcurrencyMultiplier(v)
	return _c
}

// SetNillableConcurrencyMultiplier sets the "concurrency_multiplier" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableConcurrencyMultiplier(v *float64) *SharedAccountListingCreate {
	if v != nil {
		_c.SetConcurrencyMultiplier(*v)
	}
	return _c
}

// SetSellRate sets the "sell_rate" field.
func (_c *SharedAccountListingCreate) SetSellRate(v float64) *SharedAccountListingCreate {
	_c.mutation.SetSellRate(v)
	return _c
}

// SetNillableSellRate sets the "sell_rate" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableSellRate(v *float64) *SharedAccountListingCreate {
	if v != nil {
		_c.SetSellRate(*v)
	}
	return _c
}

// SetFeeRateOverride sets the "fee_rate_override" field.
func (_c *SharedAccountListingCreate) SetFeeRateOverride(v float64) *SharedAccountListingCreate {
	_c.mutation.SetFeeRateOverride(v)
	return _c
}

// SetNillableFeeRateOverride sets the "fee_rate_override" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableFeeRateOverride(v *float64) *SharedAccountListingCreate {
	if v != nil {
		_c.SetFeeRateOverride(*v)
	}
	return _c
}

// SetTotalCallCount sets the "total_call_count" field.
func (_c *SharedAccountListingCreate) SetTotalCallCount(v int64) *SharedAccountListingCreate {
	_c.mutation.SetTotalCallCount(v)
	return _c
}

// SetNillableTotalCallCount sets the "total_call_count" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableTotalCallCount(v *int64) *SharedAccountListingCreate {
	if v != nil {
		_c.SetTotalCallCount(*v)
	}
	return _c
}

// SetLastCalledAt sets the "last_called_at" field.
func (_c *SharedAccountListingCreate) SetLastCalledAt(v time.Time) *SharedAccountListingCreate {
	_c.mutation.SetLastCalledAt(v)
	return _c
}

// SetNillableLastCalledAt sets the "last_called_at" field if the given value is not nil.
func (_c *SharedAccountListingCreate) SetNillableLastCalledAt(v *time.Time) *SharedAccountListingCreate {
	if v != nil {
		_c.SetLastCalledAt(*v)
	}
	return _c
}

// Mutation returns the SharedAccountListingMutation object of the builder.
func (_c *SharedAccountListingCreate) Mutation() *SharedAccountListingMutation {
	return _c.mutation
}

// Save creates the SharedAccountListing in the database.
func (_c *SharedAccountListingCreate) Save(ctx context.Context) (*SharedAccountListing, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SharedAccountListingCreate) SaveX(ctx context.Context) *SharedAccountListing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedAccountListingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedAccountListingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SharedAccountListingCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sharedaccountlisting.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedaccountlisting.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sharedaccountlisting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if sharedaccountlisting.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedaccountlisting.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedaccountlisting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sharedaccountlisting.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ConcurrencyLimit(); !ok {
		v := sharedaccountlisting.DefaultConcurrencyLimit
		_c.mutation.SetConcurrencyLimit(v)
	}
	if _, ok := _c.mutation.ConcurrencyMultiplier(); !ok {
		v := sharedaccountlisting.DefaultConcurrencyMultiplier
		_c.mutation.SetConcurrencyMultiplier(v)
	}
	if _, ok := _c.mutation.SellRate(); !ok {
		v := sharedaccountlisting.DefaultSellRate
		_c.mutation.SetSellRate(v)
	}
	if _, ok := _c.mutation.TotalCallCount(); !ok {
		v := sharedaccountlisting.DefaultTotalCallCount
		_c.mutation.SetTotalCallCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SharedAccountListingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SharedAccountListing.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SharedAccountListing.updated_at"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "SharedAccountListing.owner_user_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "SharedAccountListing.account_id"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "SharedAccountListing.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := sharedaccountlisting.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "SharedAccountListing.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := sharedaccountlisting.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SharedAccountListing.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sharedaccountlisting.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConcurrencyLimit(); !ok {
		return &ValidationError{Name: "concurrency_limit", err: errors.New(`ent: missing required field "SharedAccountListing.concurrency_limit"`)}
	}
	if _, ok := _c.mutation.ConcurrencyMultiplier(); !ok {
		return &ValidationError{Name: "concurrency_multiplier", err: errors.New(`ent: missing required field "SharedAccountListing.concurrency_multiplier"`)}
	}
	if _, ok := _c.mutation.SellRate(); !ok {
		return &ValidationError{Name: "sell_rate", err: errors.New(`ent: missing required field "SharedAccountListing.sell_rate"`)}
	}
	if _, ok := _c.mutation.TotalCallCount(); !ok {
		return &ValidationError{Name: "total_call_count", err: errors.New(`ent: missing required field "SharedAccountListing.total_call_count"`)}
	}
	return nil
}

func (_c *SharedAccountListingCreate) sqlSave(ctx context.Context) (*SharedAccountListing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SharedAccountListingCreate) createSpec() (*SharedAccountListing, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedAccountListing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sharedaccountlisting.Table, sqlgraph.NewFieldSpec(sharedaccountlisting.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(sharedaccountlisting.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(sharedaccountlisting.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(sharedaccountlisting.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(sharedaccountlisting.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sharedaccountlisting.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProxyConfigEncrypted(); ok {
		_spec.SetField(sharedaccountlisting.FieldProxyConfigEncrypted, field.TypeString, value)
		_node.ProxyConfigEncrypted = &value
	}
	if value, ok := _c.mutation.ConcurrencyLimit(); ok {
		_spec.SetField(sharedaccountlisting.FieldConcurrencyLimit, field.TypeInt, value)
		_node.ConcurrencyLimit = value
	}
	if value, ok := _c.mutation.ConcurrencyMultiplier(); ok {
		_spec.SetField(sharedaccountlisting.FieldConcurrencyMultiplier, field.TypeFloat64, value)
		_node.ConcurrencyMultiplier = value
	}
	if value, ok := _c.mutation.SellRate(); ok {
		_spec.SetField(sharedaccountlisting.FieldSellRate, field.TypeFloat64, value)
		_node.SellRate = value
	}
	if value, ok := _c.mutation.FeeRateOverride(); ok {
		_spec.SetField(sharedaccountlisting.FieldFeeRateOverride, field.TypeFloat64, value)
		_node.FeeRateOverride = &value
	}
	if value, ok := _c.mutation.TotalCallCount(); ok {
		_spec.SetField(sharedaccountlisting.FieldTotalCallCount, field.TypeInt64, value)
		_node.TotalCallCount = value
	}
	if value, ok := _c.mutation.LastCalledAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldLastCalledAt, field.TypeTime, value)
		_node.LastCalledAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedAccountListing.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedAccountListingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SharedAccountListingCreate) OnConflict(opts ...sql.ConflictOption) *SharedAccountListingUpsertOne {
	_c.conflict = opts
	return &SharedAccountListingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedAccountListing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharedAccountListingCreate) OnConflictColumns(columns ...string) *SharedAccountListingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharedAccountListingUpsertOne{
		create: _c,
	}
}

type (
	// SharedAccountListingUpsertOne is the builder for "upsert"-ing
	//  one SharedAccountListing node.
	SharedAccountListingUpsertOne struct {
		create *SharedAccountListingCreate
	}

	// SharedAccountListingUpsert is the "OnConflict" setter.
	SharedAccountListingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountListingUpsert) SetUpdatedAt(v time.Time) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateUpdatedAt() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedAccountListingUpsert) SetDeletedAt(v time.Time) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateDeletedAt() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedAccountListingUpsert) ClearDeletedAt() *SharedAccountListingUpsert {
	u.SetNull(sharedaccountlisting.FieldDeletedAt)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SharedAccountListingUpsert) SetOwnerUserID(v int64) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateOwnerUserID() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SharedAccountListingUpsert) AddOwnerUserID(v int64) *SharedAccountListingUpsert {
	u.Add(sharedaccountlisting.FieldOwnerUserID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *SharedAccountListingUpsert) SetAccountID(v int64) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateAccountID() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *SharedAccountListingUpsert) AddAccountID(v int64) *SharedAccountListingUpsert {
	u.Add(sharedaccountlisting.FieldAccountID, v)
	return u
}

// SetPlatform sets the "platform" field.
func (u *SharedAccountListingUpsert) SetPlatform(v string) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdatePlatform() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldPlatform)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *SharedAccountListingUpsert) SetDisplayName(v string) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateDisplayName() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldDisplayName)
	return u
}

// SetStatus sets the "status" field.
func (u *SharedAccountListingUpsert) SetStatus(v string) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateStatus() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldStatus)
	return u
}

// SetProxyConfigEncrypted sets the "proxy_config_encrypted" field.
func (u *SharedAccountListingUpsert) SetProxyConfigEncrypted(v string) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldProxyConfigEncrypted, v)
	return u
}

// UpdateProxyConfigEncrypted sets the "proxy_config_encrypted" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateProxyConfigEncrypted() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldProxyConfigEncrypted)
	return u
}

// ClearProxyConfigEncrypted clears the value of the "proxy_config_encrypted" field.
func (u *SharedAccountListingUpsert) ClearProxyConfigEncrypted() *SharedAccountListingUpsert {
	u.SetNull(sharedaccountlisting.FieldProxyConfigEncrypted)
	return u
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (u *SharedAccountListingUpsert) SetConcurrencyLimit(v int) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldConcurrencyLimit, v)
	return u
}

// UpdateConcurrencyLimit sets the "concurrency_limit" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateConcurrencyLimit() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldConcurrencyLimit)
	return u
}

// AddConcurrencyLimit adds v to the "concurrency_limit" field.
func (u *SharedAccountListingUpsert) AddConcurrencyLimit(v int) *SharedAccountListingUpsert {
	u.Add(sharedaccountlisting.FieldConcurrencyLimit, v)
	return u
}

// SetConcurrencyMultiplier sets the "concurrency_multiplier" field.
func (u *SharedAccountListingUpsert) SetConcurrencyMultiplier(v float64) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldConcurrencyMultiplier, v)
	return u
}

// UpdateConcurrencyMultiplier sets the "concurrency_multiplier" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateConcurrencyMultiplier() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldConcurrencyMultiplier)
	return u
}

// AddConcurrencyMultiplier adds v to the "concurrency_multiplier" field.
func (u *SharedAccountListingUpsert) AddConcurrencyMultiplier(v float64) *SharedAccountListingUpsert {
	u.Add(sharedaccountlisting.FieldConcurrencyMultiplier, v)
	return u
}

// SetSellRate sets the "sell_rate" field.
func (u *SharedAccountListingUpsert) SetSellRate(v float64) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldSellRate, v)
	return u
}

// UpdateSellRate sets the "sell_rate" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateSellRate() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldSellRate)
	return u
}

// AddSellRate adds v to the "sell_rate" field.
func (u *SharedAccountListingUpsert) AddSellRate(v float64) *SharedAccountListingUpsert {
	u.Add(sharedaccountlisting.FieldSellRate, v)
	return u
}

// SetFeeRateOverride sets the "fee_rate_override" field.
func (u *SharedAccountListingUpsert) SetFeeRateOverride(v float64) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldFeeRateOverride, v)
	return u
}

// UpdateFeeRateOverride sets the "fee_rate_override" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateFeeRateOverride() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldFeeRateOverride)
	return u
}

// AddFeeRateOverride adds v to the "fee_rate_override" field.
func (u *SharedAccountListingUpsert) AddFeeRateOverride(v float64) *SharedAccountListingUpsert {
	u.Add(sharedaccountlisting.FieldFeeRateOverride, v)
	return u
}

// ClearFeeRateOverride clears the value of the "fee_rate_override" field.
func (u *SharedAccountListingUpsert) ClearFeeRateOverride() *SharedAccountListingUpsert {
	u.SetNull(sharedaccountlisting.FieldFeeRateOverride)
	return u
}

// SetTotalCallCount sets the "total_call_count" field.
func (u *SharedAccountListingUpsert) SetTotalCallCount(v int64) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldTotalCallCount, v)
	return u
}

// UpdateTotalCallCount sets the "total_call_count" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateTotalCallCount() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldTotalCallCount)
	return u
}

// AddTotalCallCount adds v to the "total_call_count" field.
func (u *SharedAccountListingUpsert) AddTotalCallCount(v int64) *SharedAccountListingUpsert {
	u.Add(sharedaccountlisting.FieldTotalCallCount, v)
	return u
}

// SetLastCalledAt sets the "last_called_at" field.
func (u *SharedAccountListingUpsert) SetLastCalledAt(v time.Time) *SharedAccountListingUpsert {
	u.Set(sharedaccountlisting.FieldLastCalledAt, v)
	return u
}

// UpdateLastCalledAt sets the "last_called_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsert) UpdateLastCalledAt() *SharedAccountListingUpsert {
	u.SetExcluded(sharedaccountlisting.FieldLastCalledAt)
	return u
}

// ClearLastCalledAt clears the value of the "last_called_at" field.
func (u *SharedAccountListingUpsert) ClearLastCalledAt() *SharedAccountListingUpsert {
	u.SetNull(sharedaccountlisting.FieldLastCalledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SharedAccountListing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedAccountListingUpsertOne) UpdateNewValues() *SharedAccountListingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sharedaccountlisting.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedAccountListing.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SharedAccountListingUpsertOne) Ignore() *SharedAccountListingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedAccountListingUpsertOne) DoNothing() *SharedAccountListingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedAccountListingCreate.OnConflict
// documentation for more info.
func (u *SharedAccountListingUpsertOne) Update(set func(*SharedAccountListingUpsert)) *SharedAccountListingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedAccountListingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountListingUpsertOne) SetUpdatedAt(v time.Time) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateUpdatedAt() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedAccountListingUpsertOne) SetDeletedAt(v time.Time) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateDeletedAt() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedAccountListingUpsertOne) ClearDeletedAt() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SharedAccountListingUpsertOne) SetOwnerUserID(v int64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SharedAccountListingUpsertOne) AddOwnerUserID(v int64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateOwnerUserID() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *SharedAccountListingUpsertOne) SetAccountID(v int64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *SharedAccountListingUpsertOne) AddAccountID(v int64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateAccountID() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateAccountID()
	})
}

// SetPlatform sets the "platform" field.
func (u *SharedAccountListingUpsertOne) SetPlatform(v string) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdatePlatform() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdatePlatform()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *SharedAccountListingUpsertOne) SetDisplayName(v string) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateDisplayName() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateDisplayName()
	})
}

// SetStatus sets the "status" field.
func (u *SharedAccountListingUpsertOne) SetStatus(v string) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateStatus() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateStatus()
	})
}

// SetProxyConfigEncrypted sets the "proxy_config_encrypted" field.
func (u *SharedAccountListingUpsertOne) SetProxyConfigEncrypted(v string) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetProxyConfigEncrypted(v)
	})
}

// UpdateProxyConfigEncrypted sets the "proxy_config_encrypted" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateProxyConfigEncrypted() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateProxyConfigEncrypted()
	})
}

// ClearProxyConfigEncrypted clears the value of the "proxy_config_encrypted" field.
func (u *SharedAccountListingUpsertOne) ClearProxyConfigEncrypted() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.ClearProxyConfigEncrypted()
	})
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (u *SharedAccountListingUpsertOne) SetConcurrencyLimit(v int) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetConcurrencyLimit(v)
	})
}

// AddConcurrencyLimit adds v to the "concurrency_limit" field.
func (u *SharedAccountListingUpsertOne) AddConcurrencyLimit(v int) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddConcurrencyLimit(v)
	})
}

// UpdateConcurrencyLimit sets the "concurrency_limit" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateConcurrencyLimit() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateConcurrencyLimit()
	})
}

// SetConcurrencyMultiplier sets the "concurrency_multiplier" field.
func (u *SharedAccountListingUpsertOne) SetConcurrencyMultiplier(v float64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetConcurrencyMultiplier(v)
	})
}

// AddConcurrencyMultiplier adds v to the "concurrency_multiplier" field.
func (u *SharedAccountListingUpsertOne) AddConcurrencyMultiplier(v float64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddConcurrencyMultiplier(v)
	})
}

// UpdateConcurrencyMultiplier sets the "concurrency_multiplier" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateConcurrencyMultiplier() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateConcurrencyMultiplier()
	})
}

// SetSellRate sets the "sell_rate" field.
func (u *SharedAccountListingUpsertOne) SetSellRate(v float64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetSellRate(v)
	})
}

// AddSellRate adds v to the "sell_rate" field.
func (u *SharedAccountListingUpsertOne) AddSellRate(v float64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddSellRate(v)
	})
}

// UpdateSellRate sets the "sell_rate" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateSellRate() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateSellRate()
	})
}

// SetFeeRateOverride sets the "fee_rate_override" field.
func (u *SharedAccountListingUpsertOne) SetFeeRateOverride(v float64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetFeeRateOverride(v)
	})
}

// AddFeeRateOverride adds v to the "fee_rate_override" field.
func (u *SharedAccountListingUpsertOne) AddFeeRateOverride(v float64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddFeeRateOverride(v)
	})
}

// UpdateFeeRateOverride sets the "fee_rate_override" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateFeeRateOverride() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateFeeRateOverride()
	})
}

// ClearFeeRateOverride clears the value of the "fee_rate_override" field.
func (u *SharedAccountListingUpsertOne) ClearFeeRateOverride() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.ClearFeeRateOverride()
	})
}

// SetTotalCallCount sets the "total_call_count" field.
func (u *SharedAccountListingUpsertOne) SetTotalCallCount(v int64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetTotalCallCount(v)
	})
}

// AddTotalCallCount adds v to the "total_call_count" field.
func (u *SharedAccountListingUpsertOne) AddTotalCallCount(v int64) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddTotalCallCount(v)
	})
}

// UpdateTotalCallCount sets the "total_call_count" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateTotalCallCount() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateTotalCallCount()
	})
}

// SetLastCalledAt sets the "last_called_at" field.
func (u *SharedAccountListingUpsertOne) SetLastCalledAt(v time.Time) *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetLastCalledAt(v)
	})
}

// UpdateLastCalledAt sets the "last_called_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsertOne) UpdateLastCalledAt() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateLastCalledAt()
	})
}

// ClearLastCalledAt clears the value of the "last_called_at" field.
func (u *SharedAccountListingUpsertOne) ClearLastCalledAt() *SharedAccountListingUpsertOne {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.ClearLastCalledAt()
	})
}

// Exec executes the query.
func (u *SharedAccountListingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedAccountListingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedAccountListingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SharedAccountListingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SharedAccountListingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SharedAccountListingCreateBulk is the builder for creating many SharedAccountListing entities in bulk.
type SharedAccountListingCreateBulk struct {
	config
	err      error
	builders []*SharedAccountListingCreate
	conflict []sql.ConflictOption
}

// Save creates the SharedAccountListing entities in the database.
func (_c *SharedAccountListingCreateBulk) Save(ctx context.Context) ([]*SharedAccountListing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SharedAccountListing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedAccountListingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SharedAccountListingCreateBulk) SaveX(ctx context.Context) []*SharedAccountListing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedAccountListingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedAccountListingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedAccountListing.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedAccountListingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SharedAccountListingCreateBulk) OnConflict(opts ...sql.ConflictOption) *SharedAccountListingUpsertBulk {
	_c.conflict = opts
	return &SharedAccountListingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedAccountListing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharedAccountListingCreateBulk) OnConflictColumns(columns ...string) *SharedAccountListingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharedAccountListingUpsertBulk{
		create: _c,
	}
}

// SharedAccountListingUpsertBulk is the builder for "upsert"-ing
// a bulk of SharedAccountListing nodes.
type SharedAccountListingUpsertBulk struct {
	create *SharedAccountListingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SharedAccountListing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedAccountListingUpsertBulk) UpdateNewValues() *SharedAccountListingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sharedaccountlisting.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedAccountListing.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SharedAccountListingUpsertBulk) Ignore() *SharedAccountListingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedAccountListingUpsertBulk) DoNothing() *SharedAccountListingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedAccountListingCreateBulk.OnConflict
// documentation for more info.
func (u *SharedAccountListingUpsertBulk) Update(set func(*SharedAccountListingUpsert)) *SharedAccountListingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedAccountListingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountListingUpsertBulk) SetUpdatedAt(v time.Time) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateUpdatedAt() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedAccountListingUpsertBulk) SetDeletedAt(v time.Time) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateDeletedAt() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedAccountListingUpsertBulk) ClearDeletedAt() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SharedAccountListingUpsertBulk) SetOwnerUserID(v int64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SharedAccountListingUpsertBulk) AddOwnerUserID(v int64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateOwnerUserID() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *SharedAccountListingUpsertBulk) SetAccountID(v int64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *SharedAccountListingUpsertBulk) AddAccountID(v int64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateAccountID() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateAccountID()
	})
}

// SetPlatform sets the "platform" field.
func (u *SharedAccountListingUpsertBulk) SetPlatform(v string) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdatePlatform() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdatePlatform()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *SharedAccountListingUpsertBulk) SetDisplayName(v string) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateDisplayName() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateDisplayName()
	})
}

// SetStatus sets the "status" field.
func (u *SharedAccountListingUpsertBulk) SetStatus(v string) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateStatus() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateStatus()
	})
}

// SetProxyConfigEncrypted sets the "proxy_config_encrypted" field.
func (u *SharedAccountListingUpsertBulk) SetProxyConfigEncrypted(v string) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetProxyConfigEncrypted(v)
	})
}

// UpdateProxyConfigEncrypted sets the "proxy_config_encrypted" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateProxyConfigEncrypted() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateProxyConfigEncrypted()
	})
}

// ClearProxyConfigEncrypted clears the value of the "proxy_config_encrypted" field.
func (u *SharedAccountListingUpsertBulk) ClearProxyConfigEncrypted() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.ClearProxyConfigEncrypted()
	})
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (u *SharedAccountListingUpsertBulk) SetConcurrencyLimit(v int) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetConcurrencyLimit(v)
	})
}

// AddConcurrencyLimit adds v to the "concurrency_limit" field.
func (u *SharedAccountListingUpsertBulk) AddConcurrencyLimit(v int) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddConcurrencyLimit(v)
	})
}

// UpdateConcurrencyLimit sets the "concurrency_limit" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateConcurrencyLimit() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateConcurrencyLimit()
	})
}

// SetConcurrencyMultiplier sets the "concurrency_multiplier" field.
func (u *SharedAccountListingUpsertBulk) SetConcurrencyMultiplier(v float64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetConcurrencyMultiplier(v)
	})
}

// AddConcurrencyMultiplier adds v to the "concurrency_multiplier" field.
func (u *SharedAccountListingUpsertBulk) AddConcurrencyMultiplier(v float64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddConcurrencyMultiplier(v)
	})
}

// UpdateConcurrencyMultiplier sets the "concurrency_multiplier" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateConcurrencyMultiplier() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateConcurrencyMultiplier()
	})
}

// SetSellRate sets the "sell_rate" field.
func (u *SharedAccountListingUpsertBulk) SetSellRate(v float64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetSellRate(v)
	})
}

// AddSellRate adds v to the "sell_rate" field.
func (u *SharedAccountListingUpsertBulk) AddSellRate(v float64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddSellRate(v)
	})
}

// UpdateSellRate sets the "sell_rate" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateSellRate() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateSellRate()
	})
}

// SetFeeRateOverride sets the "fee_rate_override" field.
func (u *SharedAccountListingUpsertBulk) SetFeeRateOverride(v float64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetFeeRateOverride(v)
	})
}

// AddFeeRateOverride adds v to the "fee_rate_override" field.
func (u *SharedAccountListingUpsertBulk) AddFeeRateOverride(v float64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddFeeRateOverride(v)
	})
}

// UpdateFeeRateOverride sets the "fee_rate_override" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateFeeRateOverride() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateFeeRateOverride()
	})
}

// ClearFeeRateOverride clears the value of the "fee_rate_override" field.
func (u *SharedAccountListingUpsertBulk) ClearFeeRateOverride() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.ClearFeeRateOverride()
	})
}

// SetTotalCallCount sets the "total_call_count" field.
func (u *SharedAccountListingUpsertBulk) SetTotalCallCount(v int64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetTotalCallCount(v)
	})
}

// AddTotalCallCount adds v to the "total_call_count" field.
func (u *SharedAccountListingUpsertBulk) AddTotalCallCount(v int64) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.AddTotalCallCount(v)
	})
}

// UpdateTotalCallCount sets the "total_call_count" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateTotalCallCount() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateTotalCallCount()
	})
}

// SetLastCalledAt sets the "last_called_at" field.
func (u *SharedAccountListingUpsertBulk) SetLastCalledAt(v time.Time) *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.SetLastCalledAt(v)
	})
}

// UpdateLastCalledAt sets the "last_called_at" field to the value that was provided on create.
func (u *SharedAccountListingUpsertBulk) UpdateLastCalledAt() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.UpdateLastCalledAt()
	})
}

// ClearLastCalledAt clears the value of the "last_called_at" field.
func (u *SharedAccountListingUpsertBulk) ClearLastCalledAt() *SharedAccountListingUpsertBulk {
	return u.Update(func(s *SharedAccountListingUpsert) {
		s.ClearLastCalledAt()
	})
}

// Exec executes the query.
func (u *SharedAccountListingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SharedAccountListingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedAccountListingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedAccountListingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
