// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountwallet"
)

// SharedAccountWalletUpdate is the builder for updating SharedAccountWallet entities.
type SharedAccountWalletUpdate struct {
	config
	hooks    []Hook
	mutation *SharedAccountWalletMutation
}

// Where appends a list predicates to the SharedAccountWalletUpdate builder.
func (_u *SharedAccountWalletUpdate) Where(ps ...predicate.SharedAccountWallet) *SharedAccountWalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SharedAccountWalletUpdate) SetUpdatedAt(v time.Time) *SharedAccountWalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SharedAccountWalletUpdate) SetUserID(v int64) *SharedAccountWalletUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SharedAccountWalletUpdate) SetNillableUserID(v *int64) *SharedAccountWalletUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SharedAccountWalletUpdate) AddUserID(v int64) *SharedAccountWalletUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPendingAmount sets the "pending_amount" field.
func (_u *SharedAccountWalletUpdate) SetPendingAmount(v float64) *SharedAccountWalletUpdate {
	_u.mutation.ResetPendingAmount()
	_u.mutation.SetPendingAmount(v)
	return _u
}

// SetNillablePendingAmount sets the "pending_amount" field if the given value is not nil.
func (_u *SharedAccountWalletUpdate) SetNillablePendingAmount(v *float64) *SharedAccountWalletUpdate {
	if v != nil {
		_u.SetPendingAmount(*v)
	}
	return _u
}

// AddPendingAmount adds value to the "pending_amount" field.
func (_u *SharedAccountWalletUpdate) AddPendingAmount(v float64) *SharedAccountWalletUpdate {
	_u.mutation.AddPendingAmount(v)
	return _u
}

// SetAvailableAmount sets the "available_amount" field.
func (_u *SharedAccountWalletUpdate) SetAvailableAmount(v float64) *SharedAccountWalletUpdate {
	_u.mutation.ResetAvailableAmount()
	_u.mutation.SetAvailableAmount(v)
	return _u
}

// SetNillableAvailableAmount sets the "available_amount" field if the given value is not nil.
func (_u *SharedAccountWalletUpdate) SetNillableAvailableAmount(v *float64) *SharedAccountWalletUpdate {
	if v != nil {
		_u.SetAvailableAmount(*v)
	}
	return _u
}

// AddAvailableAmount adds value to the "available_amount" field.
func (_u *SharedAccountWalletUpdate) AddAvailableAmount(v float64) *SharedAccountWalletUpdate {
	_u.mutation.AddAvailableAmount(v)
	return _u
}

// SetFrozenAmount sets the "frozen_amount" field.
func (_u *SharedAccountWalletUpdate) SetFrozenAmount(v float64) *SharedAccountWalletUpdate {
	_u.mutation.ResetFrozenAmount()
	_u.mutation.SetFrozenAmount(v)
	return _u
}

// SetNillableFrozenAmount sets the "frozen_amount" field if the given value is not nil.
func (_u *SharedAccountWalletUpdate) SetNillableFrozenAmount(v *float64) *SharedAccountWalletUpdate {
	if v != nil {
		_u.SetFrozenAmount(*v)
	}
	return _u
}

// AddFrozenAmount adds value to the "frozen_amount" field.
func (_u *SharedAccountWalletUpdate) AddFrozenAmount(v float64) *SharedAccountWalletUpdate {
	_u.mutation.AddFrozenAmount(v)
	return _u
}

// SetTotalEarned sets the "total_earned" field.
func (_u *SharedAccountWalletUpdate) SetTotalEarned(v float64) *SharedAccountWalletUpdate {
	_u.mutation.ResetTotalEarned()
	_u.mutation.SetTotalEarned(v)
	return _u
}

// SetNillableTotalEarned sets the "total_earned" field if the given value is not nil.
func (_u *SharedAccountWalletUpdate) SetNillableTotalEarned(v *float64) *SharedAccountWalletUpdate {
	if v != nil {
		_u.SetTotalEarned(*v)
	}
	return _u
}

// AddTotalEarned adds value to the "total_earned" field.
func (_u *SharedAccountWalletUpdate) AddTotalEarned(v float64) *SharedAccountWalletUpdate {
	_u.mutation.AddTotalEarned(v)
	return _u
}

// SetTotalTransferred sets the "total_transferred" field.
func (_u *SharedAccountWalletUpdate) SetTotalTransferred(v float64) *SharedAccountWalletUpdate {
	_u.mutation.ResetTotalTransferred()
	_u.mutation.SetTotalTransferred(v)
	return _u
}

// SetNillableTotalTransferred sets the "total_transferred" field if the given value is not nil.
func (_u *SharedAccountWalletUpdate) SetNillableTotalTransferred(v *float64) *SharedAccountWalletUpdate {
	if v != nil {
		_u.SetTotalTransferred(*v)
	}
	return _u
}

// AddTotalTransferred adds value to the "total_transferred" field.
func (_u *SharedAccountWalletUpdate) AddTotalTransferred(v float64) *SharedAccountWalletUpdate {
	_u.mutation.AddTotalTransferred(v)
	return _u
}

// Mutation returns the SharedAccountWalletMutation object of the builder.
func (_u *SharedAccountWalletUpdate) Mutation() *SharedAccountWalletMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SharedAccountWalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedAccountWalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SharedAccountWalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedAccountWalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SharedAccountWalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sharedaccountwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SharedAccountWalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sharedaccountwallet.Table, sharedaccountwallet.Columns, sqlgraph.NewFieldSpec(sharedaccountwallet.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(sharedaccountwallet.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(sharedaccountwallet.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PendingAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldPendingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPendingAmount(); ok {
		_spec.AddField(sharedaccountwallet.FieldPendingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AvailableAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldAvailableAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvailableAmount(); ok {
		_spec.AddField(sharedaccountwallet.FieldAvailableAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrozenAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldFrozenAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenAmount(); ok {
		_spec.AddField(sharedaccountwallet.FieldFrozenAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalEarned(); ok {
		_spec.SetField(sharedaccountwallet.FieldTotalEarned, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalEarned(); ok {
		_spec.AddField(sharedaccountwallet.FieldTotalEarned, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalTransferred(); ok {
		_spec.SetField(sharedaccountwallet.FieldTotalTransferred, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalTransferred(); ok {
		_spec.AddField(sharedaccountwallet.FieldTotalTransferred, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedaccountwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SharedAccountWalletUpdateOne is the builder for updating a single SharedAccountWallet entity.
type SharedAccountWalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SharedAccountWalletMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SharedAccountWalletUpdateOne) SetUpdatedAt(v time.Time) *SharedAccountWalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SharedAccountWalletUpdateOne) SetUserID(v int64) *SharedAccountWalletUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SharedAccountWalletUpdateOne) SetNillableUserID(v *int64) *SharedAccountWalletUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SharedAccountWalletUpdateOne) AddUserID(v int64) *SharedAccountWalletUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPendingAmount sets the "pending_amount" field.
func (_u *SharedAccountWalletUpdateOne) SetPendingAmount(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.ResetPendingAmount()
	_u.mutation.SetPendingAmount(v)
	return _u
}

// SetNillablePendingAmount sets the "pending_amount" field if the given value is not nil.
func (_u *SharedAccountWalletUpdateOne) SetNillablePendingAmount(v *float64) *SharedAccountWalletUpdateOne {
	if v != nil {
		_u.SetPendingAmount(*v)
	}
	return _u
}

// AddPendingAmount adds value to the "pending_amount" field.
func (_u *SharedAccountWalletUpdateOne) AddPendingAmount(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.AddPendingAmount(v)
	return _u
}

// SetAvailableAmount sets the "available_amount" field.
func (_u *SharedAccountWalletUpdateOne) SetAvailableAmount(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.ResetAvailableAmount()
	_u.mutation.SetAvailableAmount(v)
	return _u
}

// SetNillableAvailableAmount sets the "available_amount" field if the given value is not nil.
func (_u *SharedAccountWalletUpdateOne) SetNillableAvailableAmount(v *float64) *SharedAccountWalletUpdateOne {
	if v != nil {
		_u.SetAvailableAmount(*v)
	}
	return _u
}

// AddAvailableAmount adds value to the "available_amount" field.
func (_u *SharedAccountWalletUpdateOne) AddAvailableAmount(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.AddAvailableAmount(v)
	return _u
}

// SetFrozenAmount sets the "frozen_amount" field.
func (_u *SharedAccountWalletUpdateOne) SetFrozenAmount(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.ResetFrozenAmount()
	_u.mutation.SetFrozenAmount(v)
	return _u
}

// SetNillableFrozenAmount sets the "frozen_amount" field if the given value is not nil.
func (_u *SharedAccountWalletUpdateOne) SetNillableFrozenAmount(v *float64) *SharedAccountWalletUpdateOne {
	if v != nil {
		_u.SetFrozenAmount(*v)
	}
	return _u
}

// AddFrozenAmount adds value to the "frozen_amount" field.
func (_u *SharedAccountWalletUpdateOne) AddFrozenAmount(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.AddFrozenAmount(v)
	return _u
}

// SetTotalEarned sets the "total_earned" field.
func (_u *SharedAccountWalletUpdateOne) SetTotalEarned(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.ResetTotalEarned()
	_u.mutation.SetTotalEarned(v)
	return _u
}

// SetNillableTotalEarned sets the "total_earned" field if the given value is not nil.
func (_u *SharedAccountWalletUpdateOne) SetNillableTotalEarned(v *float64) *SharedAccountWalletUpdateOne {
	if v != nil {
		_u.SetTotalEarned(*v)
	}
	return _u
}

// AddTotalEarned adds value to the "total_earned" field.
func (_u *SharedAccountWalletUpdateOne) AddTotalEarned(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.AddTotalEarned(v)
	return _u
}

// SetTotalTransferred sets the "total_transferred" field.
func (_u *SharedAccountWalletUpdateOne) SetTotalTransferred(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.ResetTotalTransferred()
	_u.mutation.SetTotalTransferred(v)
	return _u
}

// SetNillableTotalTransferred sets the "total_transferred" field if the given value is not nil.
func (_u *SharedAccountWalletUpdateOne) SetNillableTotalTransferred(v *float64) *SharedAccountWalletUpdateOne {
	if v != nil {
		_u.SetTotalTransferred(*v)
	}
	return _u
}

// AddTotalTransferred adds value to the "total_transferred" field.
func (_u *SharedAccountWalletUpdateOne) AddTotalTransferred(v float64) *SharedAccountWalletUpdateOne {
	_u.mutation.AddTotalTransferred(v)
	return _u
}

// Mutation returns the SharedAccountWalletMutation object of the builder.
func (_u *SharedAccountWalletUpdateOne) Mutation() *SharedAccountWalletMutation {
	return _u.mutation
}

// Where appends a list predicates to the SharedAccountWalletUpdate builder.
func (_u *SharedAccountWalletUpdateOne) Where(ps ...predicate.SharedAccountWallet) *SharedAccountWalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SharedAccountWalletUpdateOne) Select(field string, fields ...string) *SharedAccountWalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SharedAccountWallet entity.
func (_u *SharedAccountWalletUpdateOne) Save(ctx context.Context) (*SharedAccountWallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedAccountWalletUpdateOne) SaveX(ctx context.Context) *SharedAccountWallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SharedAccountWalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedAccountWalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SharedAccountWalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sharedaccountwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SharedAccountWalletUpdateOne) sqlSave(ctx context.Context) (_node *SharedAccountWallet, err error) {
	_spec := sqlgraph.NewUpdateSpec(sharedaccountwallet.Table, sharedaccountwallet.Columns, sqlgraph.NewFieldSpec(sharedaccountwallet.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharedAccountWallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedaccountwallet.FieldID)
		for _, f := range fields {
			if !sharedaccountwallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharedaccountwallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(sharedaccountwallet.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(sharedaccountwallet.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PendingAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldPendingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPendingAmount(); ok {
		_spec.AddField(sharedaccountwallet.FieldPendingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AvailableAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldAvailableAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvailableAmount(); ok {
		_spec.AddField(sharedaccountwallet.FieldAvailableAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrozenAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldFrozenAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenAmount(); ok {
		_spec.AddField(sharedaccountwallet.FieldFrozenAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalEarned(); ok {
		_spec.SetField(sharedaccountwallet.FieldTotalEarned, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalEarned(); ok {
		_spec.AddField(sharedaccountwallet.FieldTotalEarned, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalTransferred(); ok {
		_spec.SetField(sharedaccountwallet.FieldTotalTransferred, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalTransferred(); ok {
		_spec.AddField(sharedaccountwallet.FieldTotalTransferred, field.TypeFloat64, value)
	}
	_node = &SharedAccountWallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedaccountwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
