// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountwallet"
)

// SharedAccountWalletDelete is the builder for deleting a SharedAccountWallet entity.
type SharedAccountWalletDelete struct {
	config
	hooks    []Hook
	mutation *SharedAccountWalletMutation
}

// Where appends a list predicates to the SharedAccountWalletDelete builder.
func (_d *SharedAccountWalletDelete) Where(ps ...predicate.SharedAccountWallet) *SharedAccountWalletDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SharedAccountWalletDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SharedAccountWalletDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SharedAccountWalletDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sharedaccountwallet.Table, sqlgraph.NewFieldSpec(sharedaccountwallet.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SharedAccountWalletDeleteOne is the builder for deleting a single SharedAccountWallet entity.
type SharedAccountWalletDeleteOne struct {
	_d *SharedAccountWalletDelete
}

// Where appends a list predicates to the SharedAccountWalletDelete builder.
func (_d *SharedAccountWalletDeleteOne) Where(ps ...predicate.SharedAccountWallet) *SharedAccountWalletDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SharedAccountWalletDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sharedaccountwallet.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SharedAccountWalletDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
