// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountlisting"
)

// SharedAccountListingUpdate is the builder for updating SharedAccountListing entities.
type SharedAccountListingUpdate struct {
	config
	hooks    []Hook
	mutation *SharedAccountListingMutation
}

// Where appends a list predicates to the SharedAccountListingUpdate builder.
func (_u *SharedAccountListingUpdate) Where(ps ...predicate.SharedAccountListing) *SharedAccountListingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SharedAccountListingUpdate) SetUpdatedAt(v time.Time) *SharedAccountListingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SharedAccountListingUpdate) SetDeletedAt(v time.Time) *SharedAccountListingUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableDeletedAt(v *time.Time) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SharedAccountListingUpdate) ClearDeletedAt() *SharedAccountListingUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *SharedAccountListingUpdate) SetOwnerUserID(v int64) *SharedAccountListingUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableOwnerUserID(v *int64) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *SharedAccountListingUpdate) AddOwnerUserID(v int64) *SharedAccountListingUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *SharedAccountListingUpdate) SetAccountID(v int64) *SharedAccountListingUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableAccountID(v *int64) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *SharedAccountListingUpdate) AddAccountID(v int64) *SharedAccountListingUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *SharedAccountListingUpdate) SetPlatform(v string) *SharedAccountListingUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillablePlatform(v *string) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SharedAccountListingUpdate) SetDisplayName(v string) *SharedAccountListingUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableDisplayName(v *string) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SharedAccountListingUpdate) SetStatus(v string) *SharedAccountListingUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableStatus(v *string) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProxyConfigEncrypted sets the "proxy_config_encrypted" field.
func (_u *SharedAccountListingUpdate) SetProxyConfigEncrypted(v string) *SharedAccountListingUpdate {
	_u.mutation.SetProxyConfigEncrypted(v)
	return _u
}

// SetNillableProxyConfigEncrypted sets the "proxy_config_encrypted" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableProxyConfigEncrypted(v *string) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetProxyConfigEncrypted(*v)
	}
	return _u
}

// ClearProxyConfigEncrypted clears the value of the "proxy_config_encrypted" field.
func (_u *SharedAccountListingUpdate) ClearProxyConfigEncrypted() *SharedAccountListingUpdate {
	_u.mutation.ClearProxyConfigEncrypted()
	return _u
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (_u *SharedAccountListingUpdate) SetConcurrencyLimit(v int) *SharedAccountListingUpdate {
	_u.mutation.ResetConcurrencyLimit()
	_u.mutation.SetConcurrencyLimit(v)
	return _u
}

// SetNillableConcurrencyLimit sets the "concurrency_limit" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableConcurrencyLimit(v *int) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetConcurrencyLimit(*v)
	}
	return _u
}

// AddConcurrencyLimit adds value to the "concurrency_limit" field.
func (_u *SharedAccountListingUpdate) AddConcurrencyLimit(v int) *SharedAccountListingUpdate {
	_u.mutation.AddConcurrencyLimit(v)
	return _u
}

// SetConcurrencyMultiplier sets the "concurrency_multiplier" field.
func (_u *SharedAccountListingUpdate) SetConcurrencyMultiplier(v float64) *SharedAccountListingUpdate {
	_u.mutation.ResetConcurrencyMultiplier()
	_u.mutation.SetConcurrencyMultiplier(v)
	return _u
}

// SetNillableConcurrencyMultiplier sets the "concurrency_multiplier" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableConcurrencyMultiplier(v *float64) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetConcurrencyMultiplier(*v)
	}
	return _u
}

// AddConcurrencyMultiplier adds value to the "concurrency_multiplier" field.
func (_u *SharedAccountListingUpdate) AddConcurrencyMultiplier(v float64) *SharedAccountListingUpdate {
	_u.mutation.AddConcurrencyMultiplier(v)
	return _u
}

// SetSellRate sets the "sell_rate" field.
func (_u *SharedAccountListingUpdate) SetSellRate(v float64) *SharedAccountListingUpdate {
	_u.mutation.ResetSellRate()
	_u.mutation.SetSellRate(v)
	return _u
}

// SetNillableSellRate sets the "sell_rate" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableSellRate(v *float64) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetSellRate(*v)
	}
	return _u
}

// AddSellRate adds value to the "sell_rate" field.
func (_u *SharedAccountListingUpdate) AddSellRate(v float64) *SharedAccountListingUpdate {
	_u.mutation.AddSellRate(v)
	return _u
}

// SetFeeRateOverride sets the "fee_rate_override" field.
func (_u *SharedAccountListingUpdate) SetFeeRateOverride(v float64) *SharedAccountListingUpdate {
	_u.mutation.ResetFeeRateOverride()
	_u.mutation.SetFeeRateOverride(v)
	return _u
}

// SetNillableFeeRateOverride sets the "fee_rate_override" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableFeeRateOverride(v *float64) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetFeeRateOverride(*v)
	}
	return _u
}

// AddFeeRateOverride adds value to the "fee_rate_override" field.
func (_u *SharedAccountListingUpdate) AddFeeRateOverride(v float64) *SharedAccountListingUpdate {
	_u.mutation.AddFeeRateOverride(v)
	return _u
}

// ClearFeeRateOverride clears the value of the "fee_rate_override" field.
func (_u *SharedAccountListingUpdate) ClearFeeRateOverride() *SharedAccountListingUpdate {
	_u.mutation.ClearFeeRateOverride()
	return _u
}

// SetTotalCallCount sets the "total_call_count" field.
func (_u *SharedAccountListingUpdate) SetTotalCallCount(v int64) *SharedAccountListingUpdate {
	_u.mutation.ResetTotalCallCount()
	_u.mutation.SetTotalCallCount(v)
	return _u
}

// SetNillableTotalCallCount sets the "total_call_count" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableTotalCallCount(v *int64) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetTotalCallCount(*v)
	}
	return _u
}

// AddTotalCallCount adds value to the "total_call_count" field.
func (_u *SharedAccountListingUpdate) AddTotalCallCount(v int64) *SharedAccountListingUpdate {
	_u.mutation.AddTotalCallCount(v)
	return _u
}

// SetLastCalledAt sets the "last_called_at" field.
func (_u *SharedAccountListingUpdate) SetLastCalledAt(v time.Time) *SharedAccountListingUpdate {
	_u.mutation.SetLastCalledAt(v)
	return _u
}

// SetNillableLastCalledAt sets the "last_called_at" field if the given value is not nil.
func (_u *SharedAccountListingUpdate) SetNillableLastCalledAt(v *time.Time) *SharedAccountListingUpdate {
	if v != nil {
		_u.SetLastCalledAt(*v)
	}
	return _u
}

// ClearLastCalledAt clears the value of the "last_called_at" field.
func (_u *SharedAccountListingUpdate) ClearLastCalledAt() *SharedAccountListingUpdate {
	_u.mutation.ClearLastCalledAt()
	return _u
}

// Mutation returns the SharedAccountListingMutation object of the builder.
func (_u *SharedAccountListingUpdate) Mutation() *SharedAccountListingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SharedAccountListingUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedAccountListingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SharedAccountListingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedAccountListingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SharedAccountListingUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sharedaccountlisting.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedaccountlisting.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedaccountlisting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharedAccountListingUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := sharedaccountlisting.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := sharedaccountlisting.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sharedaccountlisting.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SharedAccountListingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedaccountlisting.Table, sharedaccountlisting.Columns, sqlgraph.NewFieldSpec(sharedaccountlisting.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sharedaccountlisting.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(sharedaccountlisting.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(sharedaccountlisting.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(sharedaccountlisting.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(sharedaccountlisting.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(sharedaccountlisting.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(sharedaccountlisting.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sharedaccountlisting.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProxyConfigEncrypted(); ok {
		_spec.SetField(sharedaccountlisting.FieldProxyConfigEncrypted, field.TypeString, value)
	}
	if _u.mutation.ProxyConfigEncryptedCleared() {
		_spec.ClearField(sharedaccountlisting.FieldProxyConfigEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.ConcurrencyLimit(); ok {
		_spec.SetField(sharedaccountlisting.FieldConcurrencyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyLimit(); ok {
		_spec.AddField(sharedaccountlisting.FieldConcurrencyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConcurrencyMultiplier(); ok {
		_spec.SetField(sharedaccountlisting.FieldConcurrencyMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyMultiplier(); ok {
		_spec.AddField(sharedaccountlisting.FieldConcurrencyMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SellRate(); ok {
		_spec.SetField(sharedaccountlisting.FieldSellRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSellRate(); ok {
		_spec.AddField(sharedaccountlisting.FieldSellRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeRateOverride(); ok {
		_spec.SetField(sharedaccountlisting.FieldFeeRateOverride, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeRateOverride(); ok {
		_spec.AddField(sharedaccountlisting.FieldFeeRateOverride, field.TypeFloat64, value)
	}
	if _u.mutation.FeeRateOverrideCleared() {
		_spec.ClearField(sharedaccountlisting.FieldFeeRateOverride, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalCallCount(); ok {
		_spec.SetField(sharedaccountlisting.FieldTotalCallCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalCallCount(); ok {
		_spec.AddField(sharedaccountlisting.FieldTotalCallCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastCalledAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldLastCalledAt, field.TypeTime, value)
	}
	if _u.mutation.LastCalledAtCleared() {
		_spec.ClearField(sharedaccountlisting.FieldLastCalledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedaccountlisting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SharedAccountListingUpdateOne is the builder for updating a single SharedAccountListing entity.
type SharedAccountListingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SharedAccountListingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SharedAccountListingUpdateOne) SetUpdatedAt(v time.Time) *SharedAccountListingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SharedAccountListingUpdateOne) SetDeletedAt(v time.Time) *SharedAccountListingUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableDeletedAt(v *time.Time) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SharedAccountListingUpdateOne) ClearDeletedAt() *SharedAccountListingUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *SharedAccountListingUpdateOne) SetOwnerUserID(v int64) *SharedAccountListingUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableOwnerUserID(v *int64) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *SharedAccountListingUpdateOne) AddOwnerUserID(v int64) *SharedAccountListingUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *SharedAccountListingUpdateOne) SetAccountID(v int64) *SharedAccountListingUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableAccountID(v *int64) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *SharedAccountListingUpdateOne) AddAccountID(v int64) *SharedAccountListingUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *SharedAccountListingUpdateOne) SetPlatform(v string) *SharedAccountListingUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillablePlatform(v *string) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SharedAccountListingUpdateOne) SetDisplayName(v string) *SharedAccountListingUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableDisplayName(v *string) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SharedAccountListingUpdateOne) SetStatus(v string) *SharedAccountListingUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableStatus(v *string) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProxyConfigEncrypted sets the "proxy_config_encrypted" field.
func (_u *SharedAccountListingUpdateOne) SetProxyConfigEncrypted(v string) *SharedAccountListingUpdateOne {
	_u.mutation.SetProxyConfigEncrypted(v)
	return _u
}

// SetNillableProxyConfigEncrypted sets the "proxy_config_encrypted" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableProxyConfigEncrypted(v *string) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetProxyConfigEncrypted(*v)
	}
	return _u
}

// ClearProxyConfigEncrypted clears the value of the "proxy_config_encrypted" field.
func (_u *SharedAccountListingUpdateOne) ClearProxyConfigEncrypted() *SharedAccountListingUpdateOne {
	_u.mutation.ClearProxyConfigEncrypted()
	return _u
}

// SetConcurrencyLimit sets the "concurrency_limit" field.
func (_u *SharedAccountListingUpdateOne) SetConcurrencyLimit(v int) *SharedAccountListingUpdateOne {
	_u.mutation.ResetConcurrencyLimit()
	_u.mutation.SetConcurrencyLimit(v)
	return _u
}

// SetNillableConcurrencyLimit sets the "concurrency_limit" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableConcurrencyLimit(v *int) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetConcurrencyLimit(*v)
	}
	return _u
}

// AddConcurrencyLimit adds value to the "concurrency_limit" field.
func (_u *SharedAccountListingUpdateOne) AddConcurrencyLimit(v int) *SharedAccountListingUpdateOne {
	_u.mutation.AddConcurrencyLimit(v)
	return _u
}

// SetConcurrencyMultiplier sets the "concurrency_multiplier" field.
func (_u *SharedAccountListingUpdateOne) SetConcurrencyMultiplier(v float64) *SharedAccountListingUpdateOne {
	_u.mutation.ResetConcurrencyMultiplier()
	_u.mutation.SetConcurrencyMultiplier(v)
	return _u
}

// SetNillableConcurrencyMultiplier sets the "concurrency_multiplier" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableConcurrencyMultiplier(v *float64) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetConcurrencyMultiplier(*v)
	}
	return _u
}

// AddConcurrencyMultiplier adds value to the "concurrency_multiplier" field.
func (_u *SharedAccountListingUpdateOne) AddConcurrencyMultiplier(v float64) *SharedAccountListingUpdateOne {
	_u.mutation.AddConcurrencyMultiplier(v)
	return _u
}

// SetSellRate sets the "sell_rate" field.
func (_u *SharedAccountListingUpdateOne) SetSellRate(v float64) *SharedAccountListingUpdateOne {
	_u.mutation.ResetSellRate()
	_u.mutation.SetSellRate(v)
	return _u
}

// SetNillableSellRate sets the "sell_rate" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableSellRate(v *float64) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetSellRate(*v)
	}
	return _u
}

// AddSellRate adds value to the "sell_rate" field.
func (_u *SharedAccountListingUpdateOne) AddSellRate(v float64) *SharedAccountListingUpdateOne {
	_u.mutation.AddSellRate(v)
	return _u
}

// SetFeeRateOverride sets the "fee_rate_override" field.
func (_u *SharedAccountListingUpdateOne) SetFeeRateOverride(v float64) *SharedAccountListingUpdateOne {
	_u.mutation.ResetFeeRateOverride()
	_u.mutation.SetFeeRateOverride(v)
	return _u
}

// SetNillableFeeRateOverride sets the "fee_rate_override" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableFeeRateOverride(v *float64) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetFeeRateOverride(*v)
	}
	return _u
}

// AddFeeRateOverride adds value to the "fee_rate_override" field.
func (_u *SharedAccountListingUpdateOne) AddFeeRateOverride(v float64) *SharedAccountListingUpdateOne {
	_u.mutation.AddFeeRateOverride(v)
	return _u
}

// ClearFeeRateOverride clears the value of the "fee_rate_override" field.
func (_u *SharedAccountListingUpdateOne) ClearFeeRateOverride() *SharedAccountListingUpdateOne {
	_u.mutation.ClearFeeRateOverride()
	return _u
}

// SetTotalCallCount sets the "total_call_count" field.
func (_u *SharedAccountListingUpdateOne) SetTotalCallCount(v int64) *SharedAccountListingUpdateOne {
	_u.mutation.ResetTotalCallCount()
	_u.mutation.SetTotalCallCount(v)
	return _u
}

// SetNillableTotalCallCount sets the "total_call_count" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableTotalCallCount(v *int64) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetTotalCallCount(*v)
	}
	return _u
}

// AddTotalCallCount adds value to the "total_call_count" field.
func (_u *SharedAccountListingUpdateOne) AddTotalCallCount(v int64) *SharedAccountListingUpdateOne {
	_u.mutation.AddTotalCallCount(v)
	return _u
}

// SetLastCalledAt sets the "last_called_at" field.
func (_u *SharedAccountListingUpdateOne) SetLastCalledAt(v time.Time) *SharedAccountListingUpdateOne {
	_u.mutation.SetLastCalledAt(v)
	return _u
}

// SetNillableLastCalledAt sets the "last_called_at" field if the given value is not nil.
func (_u *SharedAccountListingUpdateOne) SetNillableLastCalledAt(v *time.Time) *SharedAccountListingUpdateOne {
	if v != nil {
		_u.SetLastCalledAt(*v)
	}
	return _u
}

// ClearLastCalledAt clears the value of the "last_called_at" field.
func (_u *SharedAccountListingUpdateOne) ClearLastCalledAt() *SharedAccountListingUpdateOne {
	_u.mutation.ClearLastCalledAt()
	return _u
}

// Mutation returns the SharedAccountListingMutation object of the builder.
func (_u *SharedAccountListingUpdateOne) Mutation() *SharedAccountListingMutation {
	return _u.mutation
}

// Where appends a list predicates to the SharedAccountListingUpdate builder.
func (_u *SharedAccountListingUpdateOne) Where(ps ...predicate.SharedAccountListing) *SharedAccountListingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SharedAccountListingUpdateOne) Select(field string, fields ...string) *SharedAccountListingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SharedAccountListing entity.
func (_u *SharedAccountListingUpdateOne) Save(ctx context.Context) (*SharedAccountListing, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedAccountListingUpdateOne) SaveX(ctx context.Context) *SharedAccountListing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SharedAccountListingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedAccountListingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SharedAccountListingUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sharedaccountlisting.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedaccountlisting.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedaccountlisting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharedAccountListingUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := sharedaccountlisting.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := sharedaccountlisting.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sharedaccountlisting.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SharedAccountListing.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SharedAccountListingUpdateOne) sqlSave(ctx context.Context) (_node *SharedAccountListing, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedaccountlisting.Table, sharedaccountlisting.Columns, sqlgraph.NewFieldSpec(sharedaccountlisting.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharedAccountListing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedaccountlisting.FieldID)
		for _, f := range fields {
			if !sharedaccountlisting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharedaccountlisting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sharedaccountlisting.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(sharedaccountlisting.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(sharedaccountlisting.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(sharedaccountlisting.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(sharedaccountlisting.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(sharedaccountlisting.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(sharedaccountlisting.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sharedaccountlisting.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProxyConfigEncrypted(); ok {
		_spec.SetField(sharedaccountlisting.FieldProxyConfigEncrypted, field.TypeString, value)
	}
	if _u.mutation.ProxyConfigEncryptedCleared() {
		_spec.ClearField(sharedaccountlisting.FieldProxyConfigEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.ConcurrencyLimit(); ok {
		_spec.SetField(sharedaccountlisting.FieldConcurrencyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyLimit(); ok {
		_spec.AddField(sharedaccountlisting.FieldConcurrencyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConcurrencyMultiplier(); ok {
		_spec.SetField(sharedaccountlisting.FieldConcurrencyMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyMultiplier(); ok {
		_spec.AddField(sharedaccountlisting.FieldConcurrencyMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SellRate(); ok {
		_spec.SetField(sharedaccountlisting.FieldSellRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSellRate(); ok {
		_spec.AddField(sharedaccountlisting.FieldSellRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeRateOverride(); ok {
		_spec.SetField(sharedaccountlisting.FieldFeeRateOverride, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeRateOverride(); ok {
		_spec.AddField(sharedaccountlisting.FieldFeeRateOverride, field.TypeFloat64, value)
	}
	if _u.mutation.FeeRateOverrideCleared() {
		_spec.ClearField(sharedaccountlisting.FieldFeeRateOverride, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalCallCount(); ok {
		_spec.SetField(sharedaccountlisting.FieldTotalCallCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalCallCount(); ok {
		_spec.AddField(sharedaccountlisting.FieldTotalCallCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastCalledAt(); ok {
		_spec.SetField(sharedaccountlisting.FieldLastCalledAt, field.TypeTime, value)
	}
	if _u.mutation.LastCalledAtCleared() {
		_spec.ClearField(sharedaccountlisting.FieldLastCalledAt, field.TypeTime)
	}
	_node = &SharedAccountListing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedaccountlisting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
