// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountwallet"
)

// SharedAccountWalletCreate is the builder for creating a SharedAccountWallet entity.
type SharedAccountWalletCreate struct {
	config
	mutation *SharedAccountWalletMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SharedAccountWalletCreate) SetCreatedAt(v time.Time) *SharedAccountWalletCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SharedAccountWalletCreate) SetNillableCreatedAt(v *time.Time) *SharedAccountWalletCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SharedAccountWalletCreate) SetUpdatedAt(v time.Time) *SharedAccountWalletCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SharedAccountWalletCreate) SetNillableUpdatedAt(v *time.Time) *SharedAccountWalletCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SharedAccountWalletCreate) SetUserID(v int64) *SharedAccountWalletCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPendingAmount sets the "pending_amount" field.
func (_c *SharedAccountWalletCreate) SetPendingAmount(v float64) *SharedAccountWalletCreate {
	_c.mutation.SetPendingAmount(v)
	return _c
}

// SetNillablePendingAmount sets the "pending_amount" field if the given value is not nil.
func (_c *SharedAccountWalletCreate) SetNillablePendingAmount(v *float64) *SharedAccountWalletCreate {
	if v != nil {
		_c.SetPendingAmount(*v)
	}
	return _c
}

// SetAvailableAmount sets the "available_amount" field.
func (_c *SharedAccountWalletCreate) SetAvailableAmount(v float64) *SharedAccountWalletCreate {
	_c.mutation.SetAvailableAmount(v)
	return _c
}

// SetNillableAvailableAmount sets the "available_amount" field if the given value is not nil.
func (_c *SharedAccountWalletCreate) SetNillableAvailableAmount(v *float64) *SharedAccountWalletCreate {
	if v != nil {
		_c.SetAvailableAmount(*v)
	}
	return _c
}

// SetFrozenAmount sets the "frozen_amount" field.
func (_c *SharedAccountWalletCreate) SetFrozenAmount(v float64) *SharedAccountWalletCreate {
	_c.mutation.SetFrozenAmount(v)
	return _c
}

// SetNillableFrozenAmount sets the "frozen_amount" field if the given value is not nil.
func (_c *SharedAccountWalletCreate) SetNillableFrozenAmount(v *float64) *SharedAccountWalletCreate {
	if v != nil {
		_c.SetFrozenAmount(*v)
	}
	return _c
}

// SetTotalEarned sets the "total_earned" field.
func (_c *SharedAccountWalletCreate) SetTotalEarned(v float64) *SharedAccountWalletCreate {
	_c.mutation.SetTotalEarned(v)
	return _c
}

// SetNillableTotalEarned sets the "total_earned" field if the given value is not nil.
func (_c *SharedAccountWalletCreate) SetNillableTotalEarned(v *float64) *SharedAccountWalletCreate {
	if v != nil {
		_c.SetTotalEarned(*v)
	}
	return _c
}

// SetTotalTransferred sets the "total_transferred" field.
func (_c *SharedAccountWalletCreate) SetTotalTransferred(v float64) *SharedAccountWalletCreate {
	_c.mutation.SetTotalTransferred(v)
	return _c
}

// SetNillableTotalTransferred sets the "total_transferred" field if the given value is not nil.
func (_c *SharedAccountWalletCreate) SetNillableTotalTransferred(v *float64) *SharedAccountWalletCreate {
	if v != nil {
		_c.SetTotalTransferred(*v)
	}
	return _c
}

// Mutation returns the SharedAccountWalletMutation object of the builder.
func (_c *SharedAccountWalletCreate) Mutation() *SharedAccountWalletMutation {
	return _c.mutation
}

// Save creates the SharedAccountWallet in the database.
func (_c *SharedAccountWalletCreate) Save(ctx context.Context) (*SharedAccountWallet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SharedAccountWalletCreate) SaveX(ctx context.Context) *SharedAccountWallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedAccountWalletCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedAccountWalletCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SharedAccountWalletCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sharedaccountwallet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sharedaccountwallet.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PendingAmount(); !ok {
		v := sharedaccountwallet.DefaultPendingAmount
		_c.mutation.SetPendingAmount(v)
	}
	if _, ok := _c.mutation.AvailableAmount(); !ok {
		v := sharedaccountwallet.DefaultAvailableAmount
		_c.mutation.SetAvailableAmount(v)
	}
	if _, ok := _c.mutation.FrozenAmount(); !ok {
		v := sharedaccountwallet.DefaultFrozenAmount
		_c.mutation.SetFrozenAmount(v)
	}
	if _, ok := _c.mutation.TotalEarned(); !ok {
		v := sharedaccountwallet.DefaultTotalEarned
		_c.mutation.SetTotalEarned(v)
	}
	if _, ok := _c.mutation.TotalTransferred(); !ok {
		v := sharedaccountwallet.DefaultTotalTransferred
		_c.mutation.SetTotalTransferred(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SharedAccountWalletCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SharedAccountWallet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SharedAccountWallet.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SharedAccountWallet.user_id"`)}
	}
	if _, ok := _c.mutation.PendingAmount(); !ok {
		return &ValidationError{Name: "pending_amount", err: errors.New(`ent: missing required field "SharedAccountWallet.pending_amount"`)}
	}
	if _, ok := _c.mutation.AvailableAmount(); !ok {
		return &ValidationError{Name: "available_amount", err: errors.New(`ent: missing required field "SharedAccountWallet.available_amount"`)}
	}
	if _, ok := _c.mutation.FrozenAmount(); !ok {
		return &ValidationError{Name: "frozen_amount", err: errors.New(`ent: missing required field "SharedAccountWallet.frozen_amount"`)}
	}
	if _, ok := _c.mutation.TotalEarned(); !ok {
		return &ValidationError{Name: "total_earned", err: errors.New(`ent: missing required field "SharedAccountWallet.total_earned"`)}
	}
	if _, ok := _c.mutation.TotalTransferred(); !ok {
		return &ValidationError{Name: "total_transferred", err: errors.New(`ent: missing required field "SharedAccountWallet.total_transferred"`)}
	}
	return nil
}

func (_c *SharedAccountWalletCreate) sqlSave(ctx context.Context) (*SharedAccountWallet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SharedAccountWalletCreate) createSpec() (*SharedAccountWallet, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedAccountWallet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sharedaccountwallet.Table, sqlgraph.NewFieldSpec(sharedaccountwallet.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sharedaccountwallet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountwallet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(sharedaccountwallet.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PendingAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldPendingAmount, field.TypeFloat64, value)
		_node.PendingAmount = value
	}
	if value, ok := _c.mutation.AvailableAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldAvailableAmount, field.TypeFloat64, value)
		_node.AvailableAmount = value
	}
	if value, ok := _c.mutation.FrozenAmount(); ok {
		_spec.SetField(sharedaccountwallet.FieldFrozenAmount, field.TypeFloat64, value)
		_node.FrozenAmount = value
	}
	if value, ok := _c.mutation.TotalEarned(); ok {
		_spec.SetField(sharedaccountwallet.FieldTotalEarned, field.TypeFloat64, value)
		_node.TotalEarned = value
	}
	if value, ok := _c.mutation.TotalTransferred(); ok {
		_spec.SetField(sharedaccountwallet.FieldTotalTransferred, field.TypeFloat64, value)
		_node.TotalTransferred = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedAccountWallet.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedAccountWalletUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SharedAccountWalletCreate) OnConflict(opts ...sql.ConflictOption) *SharedAccountWalletUpsertOne {
	_c.conflict = opts
	return &SharedAccountWalletUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedAccountWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharedAccountWalletCreate) OnConflictColumns(columns ...string) *SharedAccountWalletUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharedAccountWalletUpsertOne{
		create: _c,
	}
}

type (
	// SharedAccountWalletUpsertOne is the builder for "upsert"-ing
	//  one SharedAccountWallet node.
	SharedAccountWalletUpsertOne struct {
		create *SharedAccountWalletCreate
	}

	// SharedAccountWalletUpsert is the "OnConflict" setter.
	SharedAccountWalletUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountWalletUpsert) SetUpdatedAt(v time.Time) *SharedAccountWalletUpsert {
	u.Set(sharedaccountwallet.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountWalletUpsert) UpdateUpdatedAt() *SharedAccountWalletUpsert {
	u.SetExcluded(sharedaccountwallet.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SharedAccountWalletUpsert) SetUserID(v int64) *SharedAccountWalletUpsert {
	u.Set(sharedaccountwallet.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SharedAccountWalletUpsert) UpdateUserID() *SharedAccountWalletUpsert {
	u.SetExcluded(sharedaccountwallet.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *SharedAccountWalletUpsert) AddUserID(v int64) *SharedAccountWalletUpsert {
	u.Add(sharedaccountwallet.FieldUserID, v)
	return u
}

// SetPendingAmount sets the "pending_amount" field.
func (u *SharedAccountWalletUpsert) SetPendingAmount(v float64) *SharedAccountWalletUpsert {
	u.Set(sharedaccountwallet.FieldPendingAmount, v)
	return u
}

// UpdatePendingAmount sets the "pending_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsert) UpdatePendingAmount() *SharedAccountWalletUpsert {
	u.SetExcluded(sharedaccountwallet.FieldPendingAmount)
	return u
}

// AddPendingAmount adds v to the "pending_amount" field.
func (u *SharedAccountWalletUpsert) AddPendingAmount(v float64) *SharedAccountWalletUpsert {
	u.Add(sharedaccountwallet.FieldPendingAmount, v)
	return u
}

// SetAvailableAmount sets the "available_amount" field.
func (u *SharedAccountWalletUpsert) SetAvailableAmount(v float64) *SharedAccountWalletUpsert {
	u.Set(sharedaccountwallet.FieldAvailableAmount, v)
	return u
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsert) UpdateAvailableAmount() *SharedAccountWalletUpsert {
	u.SetExcluded(sharedaccountwallet.FieldAvailableAmount)
	return u
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *SharedAccountWalletUpsert) AddAvailableAmount(v float64) *SharedAccountWalletUpsert {
	u.Add(sharedaccountwallet.FieldAvailableAmount, v)
	return u
}

// SetFrozenAmount sets the "frozen_amount" field.
func (u *SharedAccountWalletUpsert) SetFrozenAmount(v float64) *SharedAccountWalletUpsert {
	u.Set(sharedaccountwallet.FieldFrozenAmount, v)
	return u
}

// UpdateFrozenAmount sets the "frozen_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsert) UpdateFrozenAmount() *SharedAccountWalletUpsert {
	u.SetExcluded(sharedaccountwallet.FieldFrozenAmount)
	return u
}

// AddFrozenAmount adds v to the "frozen_amount" field.
func (u *SharedAccountWalletUpsert) AddFrozenAmount(v float64) *SharedAccountWalletUpsert {
	u.Add(sharedaccountwallet.FieldFrozenAmount, v)
	return u
}

// SetTotalEarned sets the "total_earned" field.
func (u *SharedAccountWalletUpsert) SetTotalEarned(v float64) *SharedAccountWalletUpsert {
	u.Set(sharedaccountwallet.FieldTotalEarned, v)
	return u
}

// UpdateTotalEarned sets the "total_earned" field to the value that was provided on create.
func (u *SharedAccountWalletUpsert) UpdateTotalEarned() *SharedAccountWalletUpsert {
	u.SetExcluded(sharedaccountwallet.FieldTotalEarned)
	return u
}

// AddTotalEarned adds v to the "total_earned" field.
func (u *SharedAccountWalletUpsert) AddTotalEarned(v float64) *SharedAccountWalletUpsert {
	u.Add(sharedaccountwallet.FieldTotalEarned, v)
	return u
}

// SetTotalTransferred sets the "total_transferred" field.
func (u *SharedAccountWalletUpsert) SetTotalTransferred(v float64) *SharedAccountWalletUpsert {
	u.Set(sharedaccountwallet.FieldTotalTransferred, v)
	return u
}

// UpdateTotalTransferred sets the "total_transferred" field to the value that was provided on create.
func (u *SharedAccountWalletUpsert) UpdateTotalTransferred() *SharedAccountWalletUpsert {
	u.SetExcluded(sharedaccountwallet.FieldTotalTransferred)
	return u
}

// AddTotalTransferred adds v to the "total_transferred" field.
func (u *SharedAccountWalletUpsert) AddTotalTransferred(v float64) *SharedAccountWalletUpsert {
	u.Add(sharedaccountwallet.FieldTotalTransferred, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SharedAccountWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedAccountWalletUpsertOne) UpdateNewValues() *SharedAccountWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sharedaccountwallet.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedAccountWallet.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SharedAccountWalletUpsertOne) Ignore() *SharedAccountWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedAccountWalletUpsertOne) DoNothing() *SharedAccountWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedAccountWalletCreate.OnConflict
// documentation for more info.
func (u *SharedAccountWalletUpsertOne) Update(set func(*SharedAccountWalletUpsert)) *SharedAccountWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedAccountWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountWalletUpsertOne) SetUpdatedAt(v time.Time) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertOne) UpdateUpdatedAt() *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SharedAccountWalletUpsertOne) SetUserID(v int64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SharedAccountWalletUpsertOne) AddUserID(v int64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertOne) UpdateUserID() *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateUserID()
	})
}

// SetPendingAmount sets the "pending_amount" field.
func (u *SharedAccountWalletUpsertOne) SetPendingAmount(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetPendingAmount(v)
	})
}

// AddPendingAmount adds v to the "pending_amount" field.
func (u *SharedAccountWalletUpsertOne) AddPendingAmount(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddPendingAmount(v)
	})
}

// UpdatePendingAmount sets the "pending_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertOne) UpdatePendingAmount() *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdatePendingAmount()
	})
}

// SetAvailableAmount sets the "available_amount" field.
func (u *SharedAccountWalletUpsertOne) SetAvailableAmount(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetAvailableAmount(v)
	})
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *SharedAccountWalletUpsertOne) AddAvailableAmount(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddAvailableAmount(v)
	})
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertOne) UpdateAvailableAmount() *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateAvailableAmount()
	})
}

// SetFrozenAmount sets the "frozen_amount" field.
func (u *SharedAccountWalletUpsertOne) SetFrozenAmount(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetFrozenAmount(v)
	})
}

// AddFrozenAmount adds v to the "frozen_amount" field.
func (u *SharedAccountWalletUpsertOne) AddFrozenAmount(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddFrozenAmount(v)
	})
}

// UpdateFrozenAmount sets the "frozen_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertOne) UpdateFrozenAmount() *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateFrozenAmount()
	})
}

// SetTotalEarned sets the "total_earned" field.
func (u *SharedAccountWalletUpsertOne) SetTotalEarned(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetTotalEarned(v)
	})
}

// AddTotalEarned adds v to the "total_earned" field.
func (u *SharedAccountWalletUpsertOne) AddTotalEarned(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddTotalEarned(v)
	})
}

// UpdateTotalEarned sets the "total_earned" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertOne) UpdateTotalEarned() *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateTotalEarned()
	})
}

// SetTotalTransferred sets the "total_transferred" field.
func (u *SharedAccountWalletUpsertOne) SetTotalTransferred(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetTotalTransferred(v)
	})
}

// AddTotalTransferred adds v to the "total_transferred" field.
func (u *SharedAccountWalletUpsertOne) AddTotalTransferred(v float64) *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddTotalTransferred(v)
	})
}

// UpdateTotalTransferred sets the "total_transferred" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertOne) UpdateTotalTransferred() *SharedAccountWalletUpsertOne {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateTotalTransferred()
	})
}

// Exec executes the query.
func (u *SharedAccountWalletUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedAccountWalletCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedAccountWalletUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SharedAccountWalletUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SharedAccountWalletUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SharedAccountWalletCreateBulk is the builder for creating many SharedAccountWallet entities in bulk.
type SharedAccountWalletCreateBulk struct {
	config
	err      error
	builders []*SharedAccountWalletCreate
	conflict []sql.ConflictOption
}

// Save creates the SharedAccountWallet entities in the database.
func (_c *SharedAccountWalletCreateBulk) Save(ctx context.Context) ([]*SharedAccountWallet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SharedAccountWallet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedAccountWalletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SharedAccountWalletCreateBulk) SaveX(ctx context.Context) []*SharedAccountWallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedAccountWalletCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedAccountWalletCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedAccountWallet.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedAccountWalletUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SharedAccountWalletCreateBulk) OnConflict(opts ...sql.ConflictOption) *SharedAccountWalletUpsertBulk {
	_c.conflict = opts
	return &SharedAccountWalletUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedAccountWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharedAccountWalletCreateBulk) OnConflictColumns(columns ...string) *SharedAccountWalletUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharedAccountWalletUpsertBulk{
		create: _c,
	}
}

// SharedAccountWalletUpsertBulk is the builder for "upsert"-ing
// a bulk of SharedAccountWallet nodes.
type SharedAccountWalletUpsertBulk struct {
	create *SharedAccountWalletCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SharedAccountWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedAccountWalletUpsertBulk) UpdateNewValues() *SharedAccountWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sharedaccountwallet.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedAccountWallet.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SharedAccountWalletUpsertBulk) Ignore() *SharedAccountWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedAccountWalletUpsertBulk) DoNothing() *SharedAccountWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedAccountWalletCreateBulk.OnConflict
// documentation for more info.
func (u *SharedAccountWalletUpsertBulk) Update(set func(*SharedAccountWalletUpsert)) *SharedAccountWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedAccountWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountWalletUpsertBulk) SetUpdatedAt(v time.Time) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertBulk) UpdateUpdatedAt() *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SharedAccountWalletUpsertBulk) SetUserID(v int64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SharedAccountWalletUpsertBulk) AddUserID(v int64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertBulk) UpdateUserID() *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateUserID()
	})
}

// SetPendingAmount sets the "pending_amount" field.
func (u *SharedAccountWalletUpsertBulk) SetPendingAmount(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetPendingAmount(v)
	})
}

// AddPendingAmount adds v to the "pending_amount" field.
func (u *SharedAccountWalletUpsertBulk) AddPendingAmount(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddPendingAmount(v)
	})
}

// UpdatePendingAmount sets the "pending_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertBulk) UpdatePendingAmount() *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdatePendingAmount()
	})
}

// SetAvailableAmount sets the "available_amount" field.
func (u *SharedAccountWalletUpsertBulk) SetAvailableAmount(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetAvailableAmount(v)
	})
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *SharedAccountWalletUpsertBulk) AddAvailableAmount(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddAvailableAmount(v)
	})
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertBulk) UpdateAvailableAmount() *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateAvailableAmount()
	})
}

// SetFrozenAmount sets the "frozen_amount" field.
func (u *SharedAccountWalletUpsertBulk) SetFrozenAmount(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetFrozenAmount(v)
	})
}

// AddFrozenAmount adds v to the "frozen_amount" field.
func (u *SharedAccountWalletUpsertBulk) AddFrozenAmount(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddFrozenAmount(v)
	})
}

// UpdateFrozenAmount sets the "frozen_amount" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertBulk) UpdateFrozenAmount() *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateFrozenAmount()
	})
}

// SetTotalEarned sets the "total_earned" field.
func (u *SharedAccountWalletUpsertBulk) SetTotalEarned(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetTotalEarned(v)
	})
}

// AddTotalEarned adds v to the "total_earned" field.
func (u *SharedAccountWalletUpsertBulk) AddTotalEarned(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddTotalEarned(v)
	})
}

// UpdateTotalEarned sets the "total_earned" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertBulk) UpdateTotalEarned() *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateTotalEarned()
	})
}

// SetTotalTransferred sets the "total_transferred" field.
func (u *SharedAccountWalletUpsertBulk) SetTotalTransferred(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.SetTotalTransferred(v)
	})
}

// AddTotalTransferred adds v to the "total_transferred" field.
func (u *SharedAccountWalletUpsertBulk) AddTotalTransferred(v float64) *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.AddTotalTransferred(v)
	})
}

// UpdateTotalTransferred sets the "total_transferred" field to the value that was provided on create.
func (u *SharedAccountWalletUpsertBulk) UpdateTotalTransferred() *SharedAccountWalletUpsertBulk {
	return u.Update(func(s *SharedAccountWalletUpsert) {
		s.UpdateTotalTransferred()
	})
}

// Exec executes the query.
func (u *SharedAccountWalletUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SharedAccountWalletCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedAccountWalletCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedAccountWalletUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
