// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountusageledger"
)

// SharedAccountUsageLedgerCreate is the builder for creating a SharedAccountUsageLedger entity.
type SharedAccountUsageLedgerCreate struct {
	config
	mutation *SharedAccountUsageLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SharedAccountUsageLedgerCreate) SetCreatedAt(v time.Time) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SharedAccountUsageLedgerCreate) SetNillableCreatedAt(v *time.Time) *SharedAccountUsageLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SharedAccountUsageLedgerCreate) SetUpdatedAt(v time.Time) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SharedAccountUsageLedgerCreate) SetNillableUpdatedAt(v *time.Time) *SharedAccountUsageLedgerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *SharedAccountUsageLedgerCreate) SetRequestID(v string) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *SharedAccountUsageLedgerCreate) SetUsageLogID(v int64) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *SharedAccountUsageLedgerCreate) SetNillableUsageLogID(v *int64) *SharedAccountUsageLedgerCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetListingID sets the "listing_id" field.
func (_c *SharedAccountUsageLedgerCreate) SetListingID(v int64) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetListingID(v)
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *SharedAccountUsageLedgerCreate) SetOwnerUserID(v int64) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (_c *SharedAccountUsageLedgerCreate) SetConsumerUserID(v int64) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetConsumerUserID(v)
	return _c
}

// SetGrossCost sets the "gross_cost" field.
func (_c *SharedAccountUsageLedgerCreate) SetGrossCost(v float64) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetGrossCost(v)
	return _c
}

// SetFeeRatePercent sets the "fee_rate_percent" field.
func (_c *SharedAccountUsageLedgerCreate) SetFeeRatePercent(v float64) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetFeeRatePercent(v)
	return _c
}

// SetPlatformFee sets the "platform_fee" field.
func (_c *SharedAccountUsageLedgerCreate) SetPlatformFee(v float64) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetPlatformFee(v)
	return _c
}

// SetOwnerAmount sets the "owner_amount" field.
func (_c *SharedAccountUsageLedgerCreate) SetOwnerAmount(v float64) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetOwnerAmount(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *SharedAccountUsageLedgerCreate) SetAction(v string) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *SharedAccountUsageLedgerCreate) SetNillableAction(v *string) *SharedAccountUsageLedgerCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetFrozenUntil sets the "frozen_until" field.
func (_c *SharedAccountUsageLedgerCreate) SetFrozenUntil(v time.Time) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetFrozenUntil(v)
	return _c
}

// SetNillableFrozenUntil sets the "frozen_until" field if the given value is not nil.
func (_c *SharedAccountUsageLedgerCreate) SetNillableFrozenUntil(v *time.Time) *SharedAccountUsageLedgerCreate {
	if v != nil {
		_c.SetFrozenUntil(*v)
	}
	return _c
}

// SetReleasedAt sets the "released_at" field.
func (_c *SharedAccountUsageLedgerCreate) SetReleasedAt(v time.Time) *SharedAccountUsageLedgerCreate {
	_c.mutation.SetReleasedAt(v)
	return _c
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_c *SharedAccountUsageLedgerCreate) SetNillableReleasedAt(v *time.Time) *SharedAccountUsageLedgerCreate {
	if v != nil {
		_c.SetReleasedAt(*v)
	}
	return _c
}

// Mutation returns the SharedAccountUsageLedgerMutation object of the builder.
func (_c *SharedAccountUsageLedgerCreate) Mutation() *SharedAccountUsageLedgerMutation {
	return _c.mutation
}

// Save creates the SharedAccountUsageLedger in the database.
func (_c *SharedAccountUsageLedgerCreate) Save(ctx context.Context) (*SharedAccountUsageLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SharedAccountUsageLedgerCreate) SaveX(ctx context.Context) *SharedAccountUsageLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedAccountUsageLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedAccountUsageLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SharedAccountUsageLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sharedaccountusageledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sharedaccountusageledger.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := sharedaccountusageledger.DefaultAction
		_c.mutation.SetAction(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SharedAccountUsageLedgerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.updated_at"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := sharedaccountusageledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SharedAccountUsageLedger.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ListingID(); !ok {
		return &ValidationError{Name: "listing_id", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.listing_id"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.owner_user_id"`)}
	}
	if _, ok := _c.mutation.ConsumerUserID(); !ok {
		return &ValidationError{Name: "consumer_user_id", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.consumer_user_id"`)}
	}
	if _, ok := _c.mutation.GrossCost(); !ok {
		return &ValidationError{Name: "gross_cost", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.gross_cost"`)}
	}
	if _, ok := _c.mutation.FeeRatePercent(); !ok {
		return &ValidationError{Name: "fee_rate_percent", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.fee_rate_percent"`)}
	}
	if _, ok := _c.mutation.PlatformFee(); !ok {
		return &ValidationError{Name: "platform_fee", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.platform_fee"`)}
	}
	if _, ok := _c.mutation.OwnerAmount(); !ok {
		return &ValidationError{Name: "owner_amount", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.owner_amount"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SharedAccountUsageLedger.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := sharedaccountusageledger.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SharedAccountUsageLedger.action": %w`, err)}
		}
	}
	return nil
}

func (_c *SharedAccountUsageLedgerCreate) sqlSave(ctx context.Context) (*SharedAccountUsageLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SharedAccountUsageLedgerCreate) createSpec() (*SharedAccountUsageLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedAccountUsageLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sharedaccountusageledger.Table, sqlgraph.NewFieldSpec(sharedaccountusageledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sharedaccountusageledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountusageledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = &value
	}
	if value, ok := _c.mutation.ListingID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldListingID, field.TypeInt64, value)
		_node.ListingID = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.ConsumerUserID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldConsumerUserID, field.TypeInt64, value)
		_node.ConsumerUserID = value
	}
	if value, ok := _c.mutation.GrossCost(); ok {
		_spec.SetField(sharedaccountusageledger.FieldGrossCost, field.TypeFloat64, value)
		_node.GrossCost = value
	}
	if value, ok := _c.mutation.FeeRatePercent(); ok {
		_spec.SetField(sharedaccountusageledger.FieldFeeRatePercent, field.TypeFloat64, value)
		_node.FeeRatePercent = value
	}
	if value, ok := _c.mutation.PlatformFee(); ok {
		_spec.SetField(sharedaccountusageledger.FieldPlatformFee, field.TypeFloat64, value)
		_node.PlatformFee = value
	}
	if value, ok := _c.mutation.OwnerAmount(); ok {
		_spec.SetField(sharedaccountusageledger.FieldOwnerAmount, field.TypeFloat64, value)
		_node.OwnerAmount = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(sharedaccountusageledger.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.FrozenUntil(); ok {
		_spec.SetField(sharedaccountusageledger.FieldFrozenUntil, field.TypeTime, value)
		_node.FrozenUntil = &value
	}
	if value, ok := _c.mutation.ReleasedAt(); ok {
		_spec.SetField(sharedaccountusageledger.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedAccountUsageLedger.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedAccountUsageLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SharedAccountUsageLedgerCreate) OnConflict(opts ...sql.ConflictOption) *SharedAccountUsageLedgerUpsertOne {
	_c.conflict = opts
	return &SharedAccountUsageLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedAccountUsageLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharedAccountUsageLedgerCreate) OnConflictColumns(columns ...string) *SharedAccountUsageLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharedAccountUsageLedgerUpsertOne{
		create: _c,
	}
}

type (
	// SharedAccountUsageLedgerUpsertOne is the builder for "upsert"-ing
	//  one SharedAccountUsageLedger node.
	SharedAccountUsageLedgerUpsertOne struct {
		create *SharedAccountUsageLedgerCreate
	}

	// SharedAccountUsageLedgerUpsert is the "OnConflict" setter.
	SharedAccountUsageLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountUsageLedgerUpsert) SetUpdatedAt(v time.Time) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateUpdatedAt() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldUpdatedAt)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *SharedAccountUsageLedgerUpsert) SetRequestID(v string) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateRequestID() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldRequestID)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsert) SetUsageLogID(v int64) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateUsageLogID() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsert) AddUsageLogID(v int64) *SharedAccountUsageLedgerUpsert {
	u.Add(sharedaccountusageledger.FieldUsageLogID, v)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsert) ClearUsageLogID() *SharedAccountUsageLedgerUpsert {
	u.SetNull(sharedaccountusageledger.FieldUsageLogID)
	return u
}

// SetListingID sets the "listing_id" field.
func (u *SharedAccountUsageLedgerUpsert) SetListingID(v int64) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldListingID, v)
	return u
}

// UpdateListingID sets the "listing_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateListingID() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldListingID)
	return u
}

// AddListingID adds v to the "listing_id" field.
func (u *SharedAccountUsageLedgerUpsert) AddListingID(v int64) *SharedAccountUsageLedgerUpsert {
	u.Add(sharedaccountusageledger.FieldListingID, v)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SharedAccountUsageLedgerUpsert) SetOwnerUserID(v int64) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateOwnerUserID() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SharedAccountUsageLedgerUpsert) AddOwnerUserID(v int64) *SharedAccountUsageLedgerUpsert {
	u.Add(sharedaccountusageledger.FieldOwnerUserID, v)
	return u
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (u *SharedAccountUsageLedgerUpsert) SetConsumerUserID(v int64) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldConsumerUserID, v)
	return u
}

// UpdateConsumerUserID sets the "consumer_user_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateConsumerUserID() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldConsumerUserID)
	return u
}

// AddConsumerUserID adds v to the "consumer_user_id" field.
func (u *SharedAccountUsageLedgerUpsert) AddConsumerUserID(v int64) *SharedAccountUsageLedgerUpsert {
	u.Add(sharedaccountusageledger.FieldConsumerUserID, v)
	return u
}

// SetGrossCost sets the "gross_cost" field.
func (u *SharedAccountUsageLedgerUpsert) SetGrossCost(v float64) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldGrossCost, v)
	return u
}

// UpdateGrossCost sets the "gross_cost" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateGrossCost() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldGrossCost)
	return u
}

// AddGrossCost adds v to the "gross_cost" field.
func (u *SharedAccountUsageLedgerUpsert) AddGrossCost(v float64) *SharedAccountUsageLedgerUpsert {
	u.Add(sharedaccountusageledger.FieldGrossCost, v)
	return u
}

// SetFeeRatePercent sets the "fee_rate_percent" field.
func (u *SharedAccountUsageLedgerUpsert) SetFeeRatePercent(v float64) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldFeeRatePercent, v)
	return u
}

// UpdateFeeRatePercent sets the "fee_rate_percent" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateFeeRatePercent() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldFeeRatePercent)
	return u
}

// AddFeeRatePercent adds v to the "fee_rate_percent" field.
func (u *SharedAccountUsageLedgerUpsert) AddFeeRatePercent(v float64) *SharedAccountUsageLedgerUpsert {
	u.Add(sharedaccountusageledger.FieldFeeRatePercent, v)
	return u
}

// SetPlatformFee sets the "platform_fee" field.
func (u *SharedAccountUsageLedgerUpsert) SetPlatformFee(v float64) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldPlatformFee, v)
	return u
}

// UpdatePlatformFee sets the "platform_fee" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdatePlatformFee() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldPlatformFee)
	return u
}

// AddPlatformFee adds v to the "platform_fee" field.
func (u *SharedAccountUsageLedgerUpsert) AddPlatformFee(v float64) *SharedAccountUsageLedgerUpsert {
	u.Add(sharedaccountusageledger.FieldPlatformFee, v)
	return u
}

// SetOwnerAmount sets the "owner_amount" field.
func (u *SharedAccountUsageLedgerUpsert) SetOwnerAmount(v float64) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldOwnerAmount, v)
	return u
}

// UpdateOwnerAmount sets the "owner_amount" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateOwnerAmount() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldOwnerAmount)
	return u
}

// AddOwnerAmount adds v to the "owner_amount" field.
func (u *SharedAccountUsageLedgerUpsert) AddOwnerAmount(v float64) *SharedAccountUsageLedgerUpsert {
	u.Add(sharedaccountusageledger.FieldOwnerAmount, v)
	return u
}

// SetAction sets the "action" field.
func (u *SharedAccountUsageLedgerUpsert) SetAction(v string) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateAction() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldAction)
	return u
}

// SetFrozenUntil sets the "frozen_until" field.
func (u *SharedAccountUsageLedgerUpsert) SetFrozenUntil(v time.Time) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldFrozenUntil, v)
	return u
}

// UpdateFrozenUntil sets the "frozen_until" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateFrozenUntil() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldFrozenUntil)
	return u
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (u *SharedAccountUsageLedgerUpsert) ClearFrozenUntil() *SharedAccountUsageLedgerUpsert {
	u.SetNull(sharedaccountusageledger.FieldFrozenUntil)
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *SharedAccountUsageLedgerUpsert) SetReleasedAt(v time.Time) *SharedAccountUsageLedgerUpsert {
	u.Set(sharedaccountusageledger.FieldReleasedAt, v)
	return u
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsert) UpdateReleasedAt() *SharedAccountUsageLedgerUpsert {
	u.SetExcluded(sharedaccountusageledger.FieldReleasedAt)
	return u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *SharedAccountUsageLedgerUpsert) ClearReleasedAt() *SharedAccountUsageLedgerUpsert {
	u.SetNull(sharedaccountusageledger.FieldReleasedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SharedAccountUsageLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedAccountUsageLedgerUpsertOne) UpdateNewValues() *SharedAccountUsageLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sharedaccountusageledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedAccountUsageLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SharedAccountUsageLedgerUpsertOne) Ignore() *SharedAccountUsageLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedAccountUsageLedgerUpsertOne) DoNothing() *SharedAccountUsageLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedAccountUsageLedgerCreate.OnConflict
// documentation for more info.
func (u *SharedAccountUsageLedgerUpsertOne) Update(set func(*SharedAccountUsageLedgerUpsert)) *SharedAccountUsageLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedAccountUsageLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetUpdatedAt(v time.Time) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateUpdatedAt() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestID sets the "request_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetRequestID(v string) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateRequestID() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateRequestID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetUsageLogID(v int64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) AddUsageLogID(v int64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateUsageLogID() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) ClearUsageLogID() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.ClearUsageLogID()
	})
}

// SetListingID sets the "listing_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetListingID(v int64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetListingID(v)
	})
}

// AddListingID adds v to the "listing_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) AddListingID(v int64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddListingID(v)
	})
}

// UpdateListingID sets the "listing_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateListingID() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateListingID()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetOwnerUserID(v int64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) AddOwnerUserID(v int64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateOwnerUserID() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetConsumerUserID(v int64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetConsumerUserID(v)
	})
}

// AddConsumerUserID adds v to the "consumer_user_id" field.
func (u *SharedAccountUsageLedgerUpsertOne) AddConsumerUserID(v int64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddConsumerUserID(v)
	})
}

// UpdateConsumerUserID sets the "consumer_user_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateConsumerUserID() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateConsumerUserID()
	})
}

// SetGrossCost sets the "gross_cost" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetGrossCost(v float64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetGrossCost(v)
	})
}

// AddGrossCost adds v to the "gross_cost" field.
func (u *SharedAccountUsageLedgerUpsertOne) AddGrossCost(v float64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddGrossCost(v)
	})
}

// UpdateGrossCost sets the "gross_cost" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateGrossCost() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateGrossCost()
	})
}

// SetFeeRatePercent sets the "fee_rate_percent" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetFeeRatePercent(v float64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetFeeRatePercent(v)
	})
}

// AddFeeRatePercent adds v to the "fee_rate_percent" field.
func (u *SharedAccountUsageLedgerUpsertOne) AddFeeRatePercent(v float64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddFeeRatePercent(v)
	})
}

// UpdateFeeRatePercent sets the "fee_rate_percent" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateFeeRatePercent() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateFeeRatePercent()
	})
}

// SetPlatformFee sets the "platform_fee" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetPlatformFee(v float64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetPlatformFee(v)
	})
}

// AddPlatformFee adds v to the "platform_fee" field.
func (u *SharedAccountUsageLedgerUpsertOne) AddPlatformFee(v float64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddPlatformFee(v)
	})
}

// UpdatePlatformFee sets the "platform_fee" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdatePlatformFee() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdatePlatformFee()
	})
}

// SetOwnerAmount sets the "owner_amount" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetOwnerAmount(v float64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetOwnerAmount(v)
	})
}

// AddOwnerAmount adds v to the "owner_amount" field.
func (u *SharedAccountUsageLedgerUpsertOne) AddOwnerAmount(v float64) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddOwnerAmount(v)
	})
}

// UpdateOwnerAmount sets the "owner_amount" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateOwnerAmount() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateOwnerAmount()
	})
}

// SetAction sets the "action" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetAction(v string) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateAction() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateAction()
	})
}

// SetFrozenUntil sets the "frozen_until" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetFrozenUntil(v time.Time) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetFrozenUntil(v)
	})
}

// UpdateFrozenUntil sets the "frozen_until" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateFrozenUntil() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateFrozenUntil()
	})
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (u *SharedAccountUsageLedgerUpsertOne) ClearFrozenUntil() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.ClearFrozenUntil()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *SharedAccountUsageLedgerUpsertOne) SetReleasedAt(v time.Time) *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertOne) UpdateReleasedAt() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *SharedAccountUsageLedgerUpsertOne) ClearReleasedAt() *SharedAccountUsageLedgerUpsertOne {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.ClearReleasedAt()
	})
}

// Exec executes the query.
func (u *SharedAccountUsageLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedAccountUsageLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedAccountUsageLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SharedAccountUsageLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SharedAccountUsageLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SharedAccountUsageLedgerCreateBulk is the builder for creating many SharedAccountUsageLedger entities in bulk.
type SharedAccountUsageLedgerCreateBulk struct {
	config
	err      error
	builders []*SharedAccountUsageLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the SharedAccountUsageLedger entities in the database.
func (_c *SharedAccountUsageLedgerCreateBulk) Save(ctx context.Context) ([]*SharedAccountUsageLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SharedAccountUsageLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedAccountUsageLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SharedAccountUsageLedgerCreateBulk) SaveX(ctx context.Context) []*SharedAccountUsageLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedAccountUsageLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedAccountUsageLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedAccountUsageLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedAccountUsageLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SharedAccountUsageLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *SharedAccountUsageLedgerUpsertBulk {
	_c.conflict = opts
	return &SharedAccountUsageLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedAccountUsageLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharedAccountUsageLedgerCreateBulk) OnConflictColumns(columns ...string) *SharedAccountUsageLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharedAccountUsageLedgerUpsertBulk{
		create: _c,
	}
}

// SharedAccountUsageLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of SharedAccountUsageLedger nodes.
type SharedAccountUsageLedgerUpsertBulk struct {
	create *SharedAccountUsageLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SharedAccountUsageLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateNewValues() *SharedAccountUsageLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sharedaccountusageledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedAccountUsageLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SharedAccountUsageLedgerUpsertBulk) Ignore() *SharedAccountUsageLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedAccountUsageLedgerUpsertBulk) DoNothing() *SharedAccountUsageLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedAccountUsageLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *SharedAccountUsageLedgerUpsertBulk) Update(set func(*SharedAccountUsageLedgerUpsert)) *SharedAccountUsageLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedAccountUsageLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetUpdatedAt(v time.Time) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateUpdatedAt() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestID sets the "request_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetRequestID(v string) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateRequestID() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateRequestID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetUsageLogID(v int64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) AddUsageLogID(v int64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateUsageLogID() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) ClearUsageLogID() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.ClearUsageLogID()
	})
}

// SetListingID sets the "listing_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetListingID(v int64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetListingID(v)
	})
}

// AddListingID adds v to the "listing_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) AddListingID(v int64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddListingID(v)
	})
}

// UpdateListingID sets the "listing_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateListingID() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateListingID()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetOwnerUserID(v int64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) AddOwnerUserID(v int64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateOwnerUserID() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetConsumerUserID(v int64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetConsumerUserID(v)
	})
}

// AddConsumerUserID adds v to the "consumer_user_id" field.
func (u *SharedAccountUsageLedgerUpsertBulk) AddConsumerUserID(v int64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddConsumerUserID(v)
	})
}

// UpdateConsumerUserID sets the "consumer_user_id" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateConsumerUserID() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateConsumerUserID()
	})
}

// SetGrossCost sets the "gross_cost" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetGrossCost(v float64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetGrossCost(v)
	})
}

// AddGrossCost adds v to the "gross_cost" field.
func (u *SharedAccountUsageLedgerUpsertBulk) AddGrossCost(v float64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddGrossCost(v)
	})
}

// UpdateGrossCost sets the "gross_cost" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateGrossCost() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateGrossCost()
	})
}

// SetFeeRatePercent sets the "fee_rate_percent" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetFeeRatePercent(v float64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetFeeRatePercent(v)
	})
}

// AddFeeRatePercent adds v to the "fee_rate_percent" field.
func (u *SharedAccountUsageLedgerUpsertBulk) AddFeeRatePercent(v float64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddFeeRatePercent(v)
	})
}

// UpdateFeeRatePercent sets the "fee_rate_percent" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateFeeRatePercent() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateFeeRatePercent()
	})
}

// SetPlatformFee sets the "platform_fee" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetPlatformFee(v float64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetPlatformFee(v)
	})
}

// AddPlatformFee adds v to the "platform_fee" field.
func (u *SharedAccountUsageLedgerUpsertBulk) AddPlatformFee(v float64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddPlatformFee(v)
	})
}

// UpdatePlatformFee sets the "platform_fee" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdatePlatformFee() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdatePlatformFee()
	})
}

// SetOwnerAmount sets the "owner_amount" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetOwnerAmount(v float64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetOwnerAmount(v)
	})
}

// AddOwnerAmount adds v to the "owner_amount" field.
func (u *SharedAccountUsageLedgerUpsertBulk) AddOwnerAmount(v float64) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.AddOwnerAmount(v)
	})
}

// UpdateOwnerAmount sets the "owner_amount" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateOwnerAmount() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateOwnerAmount()
	})
}

// SetAction sets the "action" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetAction(v string) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateAction() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateAction()
	})
}

// SetFrozenUntil sets the "frozen_until" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetFrozenUntil(v time.Time) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetFrozenUntil(v)
	})
}

// UpdateFrozenUntil sets the "frozen_until" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateFrozenUntil() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateFrozenUntil()
	})
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (u *SharedAccountUsageLedgerUpsertBulk) ClearFrozenUntil() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.ClearFrozenUntil()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *SharedAccountUsageLedgerUpsertBulk) SetReleasedAt(v time.Time) *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *SharedAccountUsageLedgerUpsertBulk) UpdateReleasedAt() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *SharedAccountUsageLedgerUpsertBulk) ClearReleasedAt() *SharedAccountUsageLedgerUpsertBulk {
	return u.Update(func(s *SharedAccountUsageLedgerUpsert) {
		s.ClearReleasedAt()
	})
}

// Exec executes the query.
func (u *SharedAccountUsageLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SharedAccountUsageLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedAccountUsageLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedAccountUsageLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
