// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountwallet"
)

// SharedAccountWallet is the model entity for the SharedAccountWallet schema.
type SharedAccountWallet struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PendingAmount holds the value of the "pending_amount" field.
	PendingAmount float64 `json:"pending_amount,omitempty"`
	// AvailableAmount holds the value of the "available_amount" field.
	AvailableAmount float64 `json:"available_amount,omitempty"`
	// FrozenAmount holds the value of the "frozen_amount" field.
	FrozenAmount float64 `json:"frozen_amount,omitempty"`
	// TotalEarned holds the value of the "total_earned" field.
	TotalEarned float64 `json:"total_earned,omitempty"`
	// TotalTransferred holds the value of the "total_transferred" field.
	TotalTransferred float64 `json:"total_transferred,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SharedAccountWallet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sharedaccountwallet.FieldPendingAmount, sharedaccountwallet.FieldAvailableAmount, sharedaccountwallet.FieldFrozenAmount, sharedaccountwallet.FieldTotalEarned, sharedaccountwallet.FieldTotalTransferred:
			values[i] = new(sql.NullFloat64)
		case sharedaccountwallet.FieldID, sharedaccountwallet.FieldUserID:
			values[i] = new(sql.NullInt64)
		case sharedaccountwallet.FieldCreatedAt, sharedaccountwallet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SharedAccountWallet fields.
func (_m *SharedAccountWallet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sharedaccountwallet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sharedaccountwallet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sharedaccountwallet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sharedaccountwallet.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case sharedaccountwallet.FieldPendingAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pending_amount", values[i])
			} else if value.Valid {
				_m.PendingAmount = value.Float64
			}
		case sharedaccountwallet.FieldAvailableAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field available_amount", values[i])
			} else if value.Valid {
				_m.AvailableAmount = value.Float64
			}
		case sharedaccountwallet.FieldFrozenAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_amount", values[i])
			} else if value.Valid {
				_m.FrozenAmount = value.Float64
			}
		case sharedaccountwallet.FieldTotalEarned:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_earned", values[i])
			} else if value.Valid {
				_m.TotalEarned = value.Float64
			}
		case sharedaccountwallet.FieldTotalTransferred:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_transferred", values[i])
			} else if value.Valid {
				_m.TotalTransferred = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SharedAccountWallet.
// This includes values selected through modifiers, order, etc.
func (_m *SharedAccountWallet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SharedAccountWallet.
// Note that you need to call SharedAccountWallet.Unwrap() before calling this method if this SharedAccountWallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SharedAccountWallet) Update() *SharedAccountWalletUpdateOne {
	return NewSharedAccountWalletClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SharedAccountWallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SharedAccountWallet) Unwrap() *SharedAccountWallet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SharedAccountWallet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SharedAccountWallet) String() string {
	var builder strings.Builder
	builder.WriteString("SharedAccountWallet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("pending_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingAmount))
	builder.WriteString(", ")
	builder.WriteString("available_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailableAmount))
	builder.WriteString(", ")
	builder.WriteString("frozen_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.FrozenAmount))
	builder.WriteString(", ")
	builder.WriteString("total_earned=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalEarned))
	builder.WriteString(", ")
	builder.WriteString("total_transferred=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTransferred))
	builder.WriteByte(')')
	return builder.String()
}

// SharedAccountWallets is a parsable slice of SharedAccountWallet.
type SharedAccountWallets []*SharedAccountWallet
