// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sharedaccountusageledger"
)

// SharedAccountUsageLedgerUpdate is the builder for updating SharedAccountUsageLedger entities.
type SharedAccountUsageLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *SharedAccountUsageLedgerMutation
}

// Where appends a list predicates to the SharedAccountUsageLedgerUpdate builder.
func (_u *SharedAccountUsageLedgerUpdate) Where(ps ...predicate.SharedAccountUsageLedger) *SharedAccountUsageLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SharedAccountUsageLedgerUpdate) SetUpdatedAt(v time.Time) *SharedAccountUsageLedgerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SharedAccountUsageLedgerUpdate) SetRequestID(v string) *SharedAccountUsageLedgerUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableRequestID(v *string) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *SharedAccountUsageLedgerUpdate) SetUsageLogID(v int64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableUsageLogID(v *int64) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *SharedAccountUsageLedgerUpdate) AddUsageLogID(v int64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *SharedAccountUsageLedgerUpdate) ClearUsageLogID() *SharedAccountUsageLedgerUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetListingID sets the "listing_id" field.
func (_u *SharedAccountUsageLedgerUpdate) SetListingID(v int64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.ResetListingID()
	_u.mutation.SetListingID(v)
	return _u
}

// SetNillableListingID sets the "listing_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableListingID(v *int64) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetListingID(*v)
	}
	return _u
}

// AddListingID adds value to the "listing_id" field.
func (_u *SharedAccountUsageLedgerUpdate) AddListingID(v int64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.AddListingID(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *SharedAccountUsageLedgerUpdate) SetOwnerUserID(v int64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableOwnerUserID(v *int64) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *SharedAccountUsageLedgerUpdate) AddOwnerUserID(v int64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (_u *SharedAccountUsageLedgerUpdate) SetConsumerUserID(v int64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.ResetConsumerUserID()
	_u.mutation.SetConsumerUserID(v)
	return _u
}

// SetNillableConsumerUserID sets the "consumer_user_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableConsumerUserID(v *int64) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetConsumerUserID(*v)
	}
	return _u
}

// AddConsumerUserID adds value to the "consumer_user_id" field.
func (_u *SharedAccountUsageLedgerUpdate) AddConsumerUserID(v int64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.AddConsumerUserID(v)
	return _u
}

// SetGrossCost sets the "gross_cost" field.
func (_u *SharedAccountUsageLedgerUpdate) SetGrossCost(v float64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.ResetGrossCost()
	_u.mutation.SetGrossCost(v)
	return _u
}

// SetNillableGrossCost sets the "gross_cost" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableGrossCost(v *float64) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetGrossCost(*v)
	}
	return _u
}

// AddGrossCost adds value to the "gross_cost" field.
func (_u *SharedAccountUsageLedgerUpdate) AddGrossCost(v float64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.AddGrossCost(v)
	return _u
}

// SetFeeRatePercent sets the "fee_rate_percent" field.
func (_u *SharedAccountUsageLedgerUpdate) SetFeeRatePercent(v float64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.ResetFeeRatePercent()
	_u.mutation.SetFeeRatePercent(v)
	return _u
}

// SetNillableFeeRatePercent sets the "fee_rate_percent" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableFeeRatePercent(v *float64) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetFeeRatePercent(*v)
	}
	return _u
}

// AddFeeRatePercent adds value to the "fee_rate_percent" field.
func (_u *SharedAccountUsageLedgerUpdate) AddFeeRatePercent(v float64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.AddFeeRatePercent(v)
	return _u
}

// SetPlatformFee sets the "platform_fee" field.
func (_u *SharedAccountUsageLedgerUpdate) SetPlatformFee(v float64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.ResetPlatformFee()
	_u.mutation.SetPlatformFee(v)
	return _u
}

// SetNillablePlatformFee sets the "platform_fee" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillablePlatformFee(v *float64) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetPlatformFee(*v)
	}
	return _u
}

// AddPlatformFee adds value to the "platform_fee" field.
func (_u *SharedAccountUsageLedgerUpdate) AddPlatformFee(v float64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.AddPlatformFee(v)
	return _u
}

// SetOwnerAmount sets the "owner_amount" field.
func (_u *SharedAccountUsageLedgerUpdate) SetOwnerAmount(v float64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.ResetOwnerAmount()
	_u.mutation.SetOwnerAmount(v)
	return _u
}

// SetNillableOwnerAmount sets the "owner_amount" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableOwnerAmount(v *float64) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetOwnerAmount(*v)
	}
	return _u
}

// AddOwnerAmount adds value to the "owner_amount" field.
func (_u *SharedAccountUsageLedgerUpdate) AddOwnerAmount(v float64) *SharedAccountUsageLedgerUpdate {
	_u.mutation.AddOwnerAmount(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *SharedAccountUsageLedgerUpdate) SetAction(v string) *SharedAccountUsageLedgerUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableAction(v *string) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetFrozenUntil sets the "frozen_until" field.
func (_u *SharedAccountUsageLedgerUpdate) SetFrozenUntil(v time.Time) *SharedAccountUsageLedgerUpdate {
	_u.mutation.SetFrozenUntil(v)
	return _u
}

// SetNillableFrozenUntil sets the "frozen_until" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableFrozenUntil(v *time.Time) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetFrozenUntil(*v)
	}
	return _u
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (_u *SharedAccountUsageLedgerUpdate) ClearFrozenUntil() *SharedAccountUsageLedgerUpdate {
	_u.mutation.ClearFrozenUntil()
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *SharedAccountUsageLedgerUpdate) SetReleasedAt(v time.Time) *SharedAccountUsageLedgerUpdate {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdate) SetNillableReleasedAt(v *time.Time) *SharedAccountUsageLedgerUpdate {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *SharedAccountUsageLedgerUpdate) ClearReleasedAt() *SharedAccountUsageLedgerUpdate {
	_u.mutation.ClearReleasedAt()
	return _u
}

// Mutation returns the SharedAccountUsageLedgerMutation object of the builder.
func (_u *SharedAccountUsageLedgerUpdate) Mutation() *SharedAccountUsageLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SharedAccountUsageLedgerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedAccountUsageLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SharedAccountUsageLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedAccountUsageLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SharedAccountUsageLedgerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sharedaccountusageledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharedAccountUsageLedgerUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := sharedaccountusageledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SharedAccountUsageLedger.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := sharedaccountusageledger.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SharedAccountUsageLedger.action": %w`, err)}
		}
	}
	return nil
}

func (_u *SharedAccountUsageLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedaccountusageledger.Table, sharedaccountusageledger.Columns, sqlgraph.NewFieldSpec(sharedaccountusageledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountusageledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(sharedaccountusageledger.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(sharedaccountusageledger.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ListingID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldListingID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedListingID(); ok {
		_spec.AddField(sharedaccountusageledger.FieldListingID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(sharedaccountusageledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConsumerUserID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldConsumerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConsumerUserID(); ok {
		_spec.AddField(sharedaccountusageledger.FieldConsumerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GrossCost(); ok {
		_spec.SetField(sharedaccountusageledger.FieldGrossCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrossCost(); ok {
		_spec.AddField(sharedaccountusageledger.FieldGrossCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeRatePercent(); ok {
		_spec.SetField(sharedaccountusageledger.FieldFeeRatePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeRatePercent(); ok {
		_spec.AddField(sharedaccountusageledger.FieldFeeRatePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PlatformFee(); ok {
		_spec.SetField(sharedaccountusageledger.FieldPlatformFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPlatformFee(); ok {
		_spec.AddField(sharedaccountusageledger.FieldPlatformFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OwnerAmount(); ok {
		_spec.SetField(sharedaccountusageledger.FieldOwnerAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOwnerAmount(); ok {
		_spec.AddField(sharedaccountusageledger.FieldOwnerAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(sharedaccountusageledger.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.FrozenUntil(); ok {
		_spec.SetField(sharedaccountusageledger.FieldFrozenUntil, field.TypeTime, value)
	}
	if _u.mutation.FrozenUntilCleared() {
		_spec.ClearField(sharedaccountusageledger.FieldFrozenUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(sharedaccountusageledger.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(sharedaccountusageledger.FieldReleasedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedaccountusageledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SharedAccountUsageLedgerUpdateOne is the builder for updating a single SharedAccountUsageLedger entity.
type SharedAccountUsageLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SharedAccountUsageLedgerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetUpdatedAt(v time.Time) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetRequestID(v string) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableRequestID(v *string) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetUsageLogID(v int64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableUsageLogID(v *int64) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) AddUsageLogID(v int64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) ClearUsageLogID() *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetListingID sets the "listing_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetListingID(v int64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ResetListingID()
	_u.mutation.SetListingID(v)
	return _u
}

// SetNillableListingID sets the "listing_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableListingID(v *int64) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetListingID(*v)
	}
	return _u
}

// AddListingID adds value to the "listing_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) AddListingID(v int64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.AddListingID(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetOwnerUserID(v int64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableOwnerUserID(v *int64) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) AddOwnerUserID(v int64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetConsumerUserID(v int64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ResetConsumerUserID()
	_u.mutation.SetConsumerUserID(v)
	return _u
}

// SetNillableConsumerUserID sets the "consumer_user_id" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableConsumerUserID(v *int64) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetConsumerUserID(*v)
	}
	return _u
}

// AddConsumerUserID adds value to the "consumer_user_id" field.
func (_u *SharedAccountUsageLedgerUpdateOne) AddConsumerUserID(v int64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.AddConsumerUserID(v)
	return _u
}

// SetGrossCost sets the "gross_cost" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetGrossCost(v float64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ResetGrossCost()
	_u.mutation.SetGrossCost(v)
	return _u
}

// SetNillableGrossCost sets the "gross_cost" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableGrossCost(v *float64) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetGrossCost(*v)
	}
	return _u
}

// AddGrossCost adds value to the "gross_cost" field.
func (_u *SharedAccountUsageLedgerUpdateOne) AddGrossCost(v float64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.AddGrossCost(v)
	return _u
}

// SetFeeRatePercent sets the "fee_rate_percent" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetFeeRatePercent(v float64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ResetFeeRatePercent()
	_u.mutation.SetFeeRatePercent(v)
	return _u
}

// SetNillableFeeRatePercent sets the "fee_rate_percent" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableFeeRatePercent(v *float64) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetFeeRatePercent(*v)
	}
	return _u
}

// AddFeeRatePercent adds value to the "fee_rate_percent" field.
func (_u *SharedAccountUsageLedgerUpdateOne) AddFeeRatePercent(v float64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.AddFeeRatePercent(v)
	return _u
}

// SetPlatformFee sets the "platform_fee" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetPlatformFee(v float64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ResetPlatformFee()
	_u.mutation.SetPlatformFee(v)
	return _u
}

// SetNillablePlatformFee sets the "platform_fee" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillablePlatformFee(v *float64) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetPlatformFee(*v)
	}
	return _u
}

// AddPlatformFee adds value to the "platform_fee" field.
func (_u *SharedAccountUsageLedgerUpdateOne) AddPlatformFee(v float64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.AddPlatformFee(v)
	return _u
}

// SetOwnerAmount sets the "owner_amount" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetOwnerAmount(v float64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ResetOwnerAmount()
	_u.mutation.SetOwnerAmount(v)
	return _u
}

// SetNillableOwnerAmount sets the "owner_amount" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableOwnerAmount(v *float64) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetOwnerAmount(*v)
	}
	return _u
}

// AddOwnerAmount adds value to the "owner_amount" field.
func (_u *SharedAccountUsageLedgerUpdateOne) AddOwnerAmount(v float64) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.AddOwnerAmount(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetAction(v string) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableAction(v *string) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetFrozenUntil sets the "frozen_until" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetFrozenUntil(v time.Time) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.SetFrozenUntil(v)
	return _u
}

// SetNillableFrozenUntil sets the "frozen_until" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableFrozenUntil(v *time.Time) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetFrozenUntil(*v)
	}
	return _u
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (_u *SharedAccountUsageLedgerUpdateOne) ClearFrozenUntil() *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ClearFrozenUntil()
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *SharedAccountUsageLedgerUpdateOne) SetReleasedAt(v time.Time) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *SharedAccountUsageLedgerUpdateOne) SetNillableReleasedAt(v *time.Time) *SharedAccountUsageLedgerUpdateOne {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *SharedAccountUsageLedgerUpdateOne) ClearReleasedAt() *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.ClearReleasedAt()
	return _u
}

// Mutation returns the SharedAccountUsageLedgerMutation object of the builder.
func (_u *SharedAccountUsageLedgerUpdateOne) Mutation() *SharedAccountUsageLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the SharedAccountUsageLedgerUpdate builder.
func (_u *SharedAccountUsageLedgerUpdateOne) Where(ps ...predicate.SharedAccountUsageLedger) *SharedAccountUsageLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SharedAccountUsageLedgerUpdateOne) Select(field string, fields ...string) *SharedAccountUsageLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SharedAccountUsageLedger entity.
func (_u *SharedAccountUsageLedgerUpdateOne) Save(ctx context.Context) (*SharedAccountUsageLedger, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedAccountUsageLedgerUpdateOne) SaveX(ctx context.Context) *SharedAccountUsageLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SharedAccountUsageLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedAccountUsageLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SharedAccountUsageLedgerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sharedaccountusageledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharedAccountUsageLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := sharedaccountusageledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SharedAccountUsageLedger.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := sharedaccountusageledger.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SharedAccountUsageLedger.action": %w`, err)}
		}
	}
	return nil
}

func (_u *SharedAccountUsageLedgerUpdateOne) sqlSave(ctx context.Context) (_node *SharedAccountUsageLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedaccountusageledger.Table, sharedaccountusageledger.Columns, sqlgraph.NewFieldSpec(sharedaccountusageledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharedAccountUsageLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedaccountusageledger.FieldID)
		for _, f := range fields {
			if !sharedaccountusageledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharedaccountusageledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedaccountusageledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(sharedaccountusageledger.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(sharedaccountusageledger.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ListingID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldListingID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedListingID(); ok {
		_spec.AddField(sharedaccountusageledger.FieldListingID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(sharedaccountusageledger.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConsumerUserID(); ok {
		_spec.SetField(sharedaccountusageledger.FieldConsumerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConsumerUserID(); ok {
		_spec.AddField(sharedaccountusageledger.FieldConsumerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GrossCost(); ok {
		_spec.SetField(sharedaccountusageledger.FieldGrossCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrossCost(); ok {
		_spec.AddField(sharedaccountusageledger.FieldGrossCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeRatePercent(); ok {
		_spec.SetField(sharedaccountusageledger.FieldFeeRatePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeRatePercent(); ok {
		_spec.AddField(sharedaccountusageledger.FieldFeeRatePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PlatformFee(); ok {
		_spec.SetField(sharedaccountusageledger.FieldPlatformFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPlatformFee(); ok {
		_spec.AddField(sharedaccountusageledger.FieldPlatformFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OwnerAmount(); ok {
		_spec.SetField(sharedaccountusageledger.FieldOwnerAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOwnerAmount(); ok {
		_spec.AddField(sharedaccountusageledger.FieldOwnerAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(sharedaccountusageledger.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.FrozenUntil(); ok {
		_spec.SetField(sharedaccountusageledger.FieldFrozenUntil, field.TypeTime, value)
	}
	if _u.mutation.FrozenUntilCleared() {
		_spec.ClearField(sharedaccountusageledger.FieldFrozenUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(sharedaccountusageledger.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(sharedaccountusageledger.FieldReleasedAt, field.TypeTime)
	}
	_node = &SharedAccountUsageLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedaccountusageledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
