// Code generated by ent, DO NOT EDIT.

package sharedaccountlisting

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sharedaccountlisting type in the database.
	Label = "shared_account_listing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProxyConfigEncrypted holds the string denoting the proxy_config_encrypted field in the database.
	FieldProxyConfigEncrypted = "proxy_config_encrypted"
	// FieldConcurrencyLimit holds the string denoting the concurrency_limit field in the database.
	FieldConcurrencyLimit = "concurrency_limit"
	// FieldConcurrencyMultiplier holds the string denoting the concurrency_multiplier field in the database.
	FieldConcurrencyMultiplier = "concurrency_multiplier"
	// FieldSellRate holds the string denoting the sell_rate field in the database.
	FieldSellRate = "sell_rate"
	// FieldFeeRateOverride holds the string denoting the fee_rate_override field in the database.
	FieldFeeRateOverride = "fee_rate_override"
	// FieldTotalCallCount holds the string denoting the total_call_count field in the database.
	FieldTotalCallCount = "total_call_count"
	// FieldLastCalledAt holds the string denoting the last_called_at field in the database.
	FieldLastCalledAt = "last_called_at"
	// Table holds the table name of the sharedaccountlisting in the database.
	Table = "shared_account_listings"
)

// Columns holds all SQL columns for sharedaccountlisting fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldOwnerUserID,
	FieldAccountID,
	FieldPlatform,
	FieldDisplayName,
	FieldStatus,
	FieldProxyConfigEncrypted,
	FieldConcurrencyLimit,
	FieldConcurrencyMultiplier,
	FieldSellRate,
	FieldFeeRateOverride,
	FieldTotalCallCount,
	FieldLastCalledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultConcurrencyLimit holds the default value on creation for the "concurrency_limit" field.
	DefaultConcurrencyLimit int
	// DefaultConcurrencyMultiplier holds the default value on creation for the "concurrency_multiplier" field.
	DefaultConcurrencyMultiplier float64
	// DefaultSellRate holds the default value on creation for the "sell_rate" field.
	DefaultSellRate float64
	// DefaultTotalCallCount holds the default value on creation for the "total_call_count" field.
	DefaultTotalCallCount int64
)

// OrderOption defines the ordering options for the SharedAccountListing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProxyConfigEncrypted orders the results by the proxy_config_encrypted field.
func ByProxyConfigEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyConfigEncrypted, opts...).ToFunc()
}

// ByConcurrencyLimit orders the results by the concurrency_limit field.
func ByConcurrencyLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrencyLimit, opts...).ToFunc()
}

// ByConcurrencyMultiplier orders the results by the concurrency_multiplier field.
func ByConcurrencyMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrencyMultiplier, opts...).ToFunc()
}

// BySellRate orders the results by the sell_rate field.
func BySellRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellRate, opts...).ToFunc()
}

// ByFeeRateOverride orders the results by the fee_rate_override field.
func ByFeeRateOverride(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeRateOverride, opts...).ToFunc()
}

// ByTotalCallCount orders the results by the total_call_count field.
func ByTotalCallCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCallCount, opts...).ToFunc()
}

// ByLastCalledAt orders the results by the last_called_at field.
func ByLastCalledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCalledAt, opts...).ToFunc()
}
