// Code generated by ent, DO NOT EDIT.

package sharedaccountlisting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldDeletedAt, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldOwnerUserID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldAccountID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldPlatform, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldDisplayName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldStatus, v))
}

// ProxyConfigEncrypted applies equality check predicate on the "proxy_config_encrypted" field. It's identical to ProxyConfigEncryptedEQ.
func ProxyConfigEncrypted(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldProxyConfigEncrypted, v))
}

// ConcurrencyLimit applies equality check predicate on the "concurrency_limit" field. It's identical to ConcurrencyLimitEQ.
func ConcurrencyLimit(v int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldConcurrencyLimit, v))
}

// ConcurrencyMultiplier applies equality check predicate on the "concurrency_multiplier" field. It's identical to ConcurrencyMultiplierEQ.
func ConcurrencyMultiplier(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldConcurrencyMultiplier, v))
}

// SellRate applies equality check predicate on the "sell_rate" field. It's identical to SellRateEQ.
func SellRate(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldSellRate, v))
}

// FeeRateOverride applies equality check predicate on the "fee_rate_override" field. It's identical to FeeRateOverrideEQ.
func FeeRateOverride(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldFeeRateOverride, v))
}

// TotalCallCount applies equality check predicate on the "total_call_count" field. It's identical to TotalCallCountEQ.
func TotalCallCount(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldTotalCallCount, v))
}

// LastCalledAt applies equality check predicate on the "last_called_at" field. It's identical to LastCalledAtEQ.
func LastCalledAt(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldLastCalledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotNull(FieldDeletedAt))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldOwnerUserID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldAccountID, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldContainsFold(FieldPlatform, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldContainsFold(FieldDisplayName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldContainsFold(FieldStatus, v))
}

// ProxyConfigEncryptedEQ applies the EQ predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedEQ(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedNEQ applies the NEQ predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedNEQ(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedIn applies the In predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedIn(vs ...string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldProxyConfigEncrypted, vs...))
}

// ProxyConfigEncryptedNotIn applies the NotIn predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedNotIn(vs ...string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldProxyConfigEncrypted, vs...))
}

// ProxyConfigEncryptedGT applies the GT predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedGT(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedGTE applies the GTE predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedGTE(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedLT applies the LT predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedLT(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedLTE applies the LTE predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedLTE(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedContains applies the Contains predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedContains(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldContains(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedHasPrefix applies the HasPrefix predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedHasPrefix(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldHasPrefix(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedHasSuffix applies the HasSuffix predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedHasSuffix(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldHasSuffix(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedIsNil applies the IsNil predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedIsNil() predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIsNull(FieldProxyConfigEncrypted))
}

// ProxyConfigEncryptedNotNil applies the NotNil predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedNotNil() predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotNull(FieldProxyConfigEncrypted))
}

// ProxyConfigEncryptedEqualFold applies the EqualFold predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedEqualFold(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEqualFold(FieldProxyConfigEncrypted, v))
}

// ProxyConfigEncryptedContainsFold applies the ContainsFold predicate on the "proxy_config_encrypted" field.
func ProxyConfigEncryptedContainsFold(v string) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldContainsFold(FieldProxyConfigEncrypted, v))
}

// ConcurrencyLimitEQ applies the EQ predicate on the "concurrency_limit" field.
func ConcurrencyLimitEQ(v int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitNEQ applies the NEQ predicate on the "concurrency_limit" field.
func ConcurrencyLimitNEQ(v int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitIn applies the In predicate on the "concurrency_limit" field.
func ConcurrencyLimitIn(vs ...int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldConcurrencyLimit, vs...))
}

// ConcurrencyLimitNotIn applies the NotIn predicate on the "concurrency_limit" field.
func ConcurrencyLimitNotIn(vs ...int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldConcurrencyLimit, vs...))
}

// ConcurrencyLimitGT applies the GT predicate on the "concurrency_limit" field.
func ConcurrencyLimitGT(v int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitGTE applies the GTE predicate on the "concurrency_limit" field.
func ConcurrencyLimitGTE(v int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitLT applies the LT predicate on the "concurrency_limit" field.
func ConcurrencyLimitLT(v int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldConcurrencyLimit, v))
}

// ConcurrencyLimitLTE applies the LTE predicate on the "concurrency_limit" field.
func ConcurrencyLimitLTE(v int) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldConcurrencyLimit, v))
}

// ConcurrencyMultiplierEQ applies the EQ predicate on the "concurrency_multiplier" field.
func ConcurrencyMultiplierEQ(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldConcurrencyMultiplier, v))
}

// ConcurrencyMultiplierNEQ applies the NEQ predicate on the "concurrency_multiplier" field.
func ConcurrencyMultiplierNEQ(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldConcurrencyMultiplier, v))
}

// ConcurrencyMultiplierIn applies the In predicate on the "concurrency_multiplier" field.
func ConcurrencyMultiplierIn(vs ...float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldConcurrencyMultiplier, vs...))
}

// ConcurrencyMultiplierNotIn applies the NotIn predicate on the "concurrency_multiplier" field.
func ConcurrencyMultiplierNotIn(vs ...float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldConcurrencyMultiplier, vs...))
}

// ConcurrencyMultiplierGT applies the GT predicate on the "concurrency_multiplier" field.
func ConcurrencyMultiplierGT(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldConcurrencyMultiplier, v))
}

// ConcurrencyMultiplierGTE applies the GTE predicate on the "concurrency_multiplier" field.
func ConcurrencyMultiplierGTE(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldConcurrencyMultiplier, v))
}

// ConcurrencyMultiplierLT applies the LT predicate on the "concurrency_multiplier" field.
func ConcurrencyMultiplierLT(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldConcurrencyMultiplier, v))
}

// ConcurrencyMultiplierLTE applies the LTE predicate on the "concurrency_multiplier" field.
func ConcurrencyMultiplierLTE(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldConcurrencyMultiplier, v))
}

// SellRateEQ applies the EQ predicate on the "sell_rate" field.
func SellRateEQ(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldSellRate, v))
}

// SellRateNEQ applies the NEQ predicate on the "sell_rate" field.
func SellRateNEQ(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldSellRate, v))
}

// SellRateIn applies the In predicate on the "sell_rate" field.
func SellRateIn(vs ...float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldSellRate, vs...))
}

// SellRateNotIn applies the NotIn predicate on the "sell_rate" field.
func SellRateNotIn(vs ...float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldSellRate, vs...))
}

// SellRateGT applies the GT predicate on the "sell_rate" field.
func SellRateGT(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldSellRate, v))
}

// SellRateGTE applies the GTE predicate on the "sell_rate" field.
func SellRateGTE(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldSellRate, v))
}

// SellRateLT applies the LT predicate on the "sell_rate" field.
func SellRateLT(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldSellRate, v))
}

// SellRateLTE applies the LTE predicate on the "sell_rate" field.
func SellRateLTE(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldSellRate, v))
}

// FeeRateOverrideEQ applies the EQ predicate on the "fee_rate_override" field.
func FeeRateOverrideEQ(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldFeeRateOverride, v))
}

// FeeRateOverrideNEQ applies the NEQ predicate on the "fee_rate_override" field.
func FeeRateOverrideNEQ(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldFeeRateOverride, v))
}

// FeeRateOverrideIn applies the In predicate on the "fee_rate_override" field.
func FeeRateOverrideIn(vs ...float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldFeeRateOverride, vs...))
}

// FeeRateOverrideNotIn applies the NotIn predicate on the "fee_rate_override" field.
func FeeRateOverrideNotIn(vs ...float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldFeeRateOverride, vs...))
}

// FeeRateOverrideGT applies the GT predicate on the "fee_rate_override" field.
func FeeRateOverrideGT(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldFeeRateOverride, v))
}

// FeeRateOverrideGTE applies the GTE predicate on the "fee_rate_override" field.
func FeeRateOverrideGTE(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldFeeRateOverride, v))
}

// FeeRateOverrideLT applies the LT predicate on the "fee_rate_override" field.
func FeeRateOverrideLT(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldFeeRateOverride, v))
}

// FeeRateOverrideLTE applies the LTE predicate on the "fee_rate_override" field.
func FeeRateOverrideLTE(v float64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldFeeRateOverride, v))
}

// FeeRateOverrideIsNil applies the IsNil predicate on the "fee_rate_override" field.
func FeeRateOverrideIsNil() predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIsNull(FieldFeeRateOverride))
}

// FeeRateOverrideNotNil applies the NotNil predicate on the "fee_rate_override" field.
func FeeRateOverrideNotNil() predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotNull(FieldFeeRateOverride))
}

// TotalCallCountEQ applies the EQ predicate on the "total_call_count" field.
func TotalCallCountEQ(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldTotalCallCount, v))
}

// TotalCallCountNEQ applies the NEQ predicate on the "total_call_count" field.
func TotalCallCountNEQ(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldTotalCallCount, v))
}

// TotalCallCountIn applies the In predicate on the "total_call_count" field.
func TotalCallCountIn(vs ...int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldTotalCallCount, vs...))
}

// TotalCallCountNotIn applies the NotIn predicate on the "total_call_count" field.
func TotalCallCountNotIn(vs ...int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldTotalCallCount, vs...))
}

// TotalCallCountGT applies the GT predicate on the "total_call_count" field.
func TotalCallCountGT(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldTotalCallCount, v))
}

// TotalCallCountGTE applies the GTE predicate on the "total_call_count" field.
func TotalCallCountGTE(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldTotalCallCount, v))
}

// TotalCallCountLT applies the LT predicate on the "total_call_count" field.
func TotalCallCountLT(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldTotalCallCount, v))
}

// TotalCallCountLTE applies the LTE predicate on the "total_call_count" field.
func TotalCallCountLTE(v int64) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldTotalCallCount, v))
}

// LastCalledAtEQ applies the EQ predicate on the "last_called_at" field.
func LastCalledAtEQ(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldEQ(FieldLastCalledAt, v))
}

// LastCalledAtNEQ applies the NEQ predicate on the "last_called_at" field.
func LastCalledAtNEQ(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNEQ(FieldLastCalledAt, v))
}

// LastCalledAtIn applies the In predicate on the "last_called_at" field.
func LastCalledAtIn(vs ...time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIn(FieldLastCalledAt, vs...))
}

// LastCalledAtNotIn applies the NotIn predicate on the "last_called_at" field.
func LastCalledAtNotIn(vs ...time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotIn(FieldLastCalledAt, vs...))
}

// LastCalledAtGT applies the GT predicate on the "last_called_at" field.
func LastCalledAtGT(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGT(FieldLastCalledAt, v))
}

// LastCalledAtGTE applies the GTE predicate on the "last_called_at" field.
func LastCalledAtGTE(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldGTE(FieldLastCalledAt, v))
}

// LastCalledAtLT applies the LT predicate on the "last_called_at" field.
func LastCalledAtLT(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLT(FieldLastCalledAt, v))
}

// LastCalledAtLTE applies the LTE predicate on the "last_called_at" field.
func LastCalledAtLTE(v time.Time) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldLTE(FieldLastCalledAt, v))
}

// LastCalledAtIsNil applies the IsNil predicate on the "last_called_at" field.
func LastCalledAtIsNil() predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldIsNull(FieldLastCalledAt))
}

// LastCalledAtNotNil applies the NotNil predicate on the "last_called_at" field.
func LastCalledAtNotNil() predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.FieldNotNull(FieldLastCalledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharedAccountListing) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharedAccountListing) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharedAccountListing) predicate.SharedAccountListing {
	return predicate.SharedAccountListing(sql.NotPredicates(p))
}
