package service

import "time"

// SharedPoolRevenueSummary is an administrator-only, aggregate view of the
// earnings generated by a shared-pool publisher. Monetary values are decimal
// strings so the API never rounds NUMERIC values through a float.
type SharedPoolRevenueSummary struct {
	UserID           int64      `json:"user_id"`
	Username         string     `json:"username,omitempty"`
	Email            string     `json:"email,omitempty"`
	ListingCount     int64      `json:"listing_count"`
	RequestCount     int64      `json:"request_count"`
	GrossAmount      string     `json:"gross_amount"`
	PlatformFee      string     `json:"platform_fee"`
	OwnerAmount      string     `json:"owner_amount"`
	Pending          string     `json:"pending"`
	Available        string     `json:"available"`
	Frozen           string     `json:"frozen"`
	TotalEarned      string     `json:"total_earned"`
	TotalTransferred string     `json:"total_transferred"`
	LastRequestAt    *time.Time `json:"last_request_at,omitempty"`
}

// SharedPoolRevenueRecord is a single settled shared-pool request. RequestID
// is the server-side deduplication hash; the consumer's original identifier is
// intentionally never persisted or exposed by this endpoint.
type SharedPoolRevenueRecord struct {
	ID             int64      `json:"id"`
	ListingID      int64      `json:"listing_id"`
	ListingName    string     `json:"listing_name"`
	Platform       string     `json:"platform"`
	OwnerUserID    int64      `json:"owner_user_id"`
	OwnerName      string     `json:"owner_name,omitempty"`
	OwnerEmail     string     `json:"owner_email,omitempty"`
	ConsumerUserID int64      `json:"consumer_user_id"`
	ConsumerName   string     `json:"consumer_name,omitempty"`
	ConsumerEmail  string     `json:"consumer_email,omitempty"`
	RequestID      string     `json:"request_id"`
	Model          string     `json:"model,omitempty"`
	ResultStatus   string     `json:"result_status,omitempty"`
	DurationMS     int64      `json:"duration_ms,omitempty"`
	GrossCost      string     `json:"gross_cost"`
	PlatformFee    string     `json:"platform_fee"`
	OwnerAmount    string     `json:"owner_amount"`
	FrozenUntil    *time.Time `json:"frozen_until,omitempty"`
	ReleasedAt     *time.Time `json:"released_at,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
}

type SharedPoolRevenueQuery struct {
	OwnerID    *int64
	ListingID  *int64
	ConsumerID *int64
	Search     string
	Model      string
	StartTime  *time.Time
	EndTime    *time.Time
	Page       int
	PageSize   int
}
