// Code generated by ent, DO NOT EDIT.

package sharedaccountwallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sharedaccountwallet type in the database.
	Label = "shared_account_wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPendingAmount holds the string denoting the pending_amount field in the database.
	FieldPendingAmount = "pending_amount"
	// FieldAvailableAmount holds the string denoting the available_amount field in the database.
	FieldAvailableAmount = "available_amount"
	// FieldFrozenAmount holds the string denoting the frozen_amount field in the database.
	FieldFrozenAmount = "frozen_amount"
	// FieldTotalEarned holds the string denoting the total_earned field in the database.
	FieldTotalEarned = "total_earned"
	// FieldTotalTransferred holds the string denoting the total_transferred field in the database.
	FieldTotalTransferred = "total_transferred"
	// Table holds the table name of the sharedaccountwallet in the database.
	Table = "shared_account_wallets"
)

// Columns holds all SQL columns for sharedaccountwallet fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldPendingAmount,
	FieldAvailableAmount,
	FieldFrozenAmount,
	FieldTotalEarned,
	FieldTotalTransferred,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultPendingAmount holds the default value on creation for the "pending_amount" field.
	DefaultPendingAmount float64
	// DefaultAvailableAmount holds the default value on creation for the "available_amount" field.
	DefaultAvailableAmount float64
	// DefaultFrozenAmount holds the default value on creation for the "frozen_amount" field.
	DefaultFrozenAmount float64
	// DefaultTotalEarned holds the default value on creation for the "total_earned" field.
	DefaultTotalEarned float64
	// DefaultTotalTransferred holds the default value on creation for the "total_transferred" field.
	DefaultTotalTransferred float64
)

// OrderOption defines the ordering options for the SharedAccountWallet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPendingAmount orders the results by the pending_amount field.
func ByPendingAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingAmount, opts...).ToFunc()
}

// ByAvailableAmount orders the results by the available_amount field.
func ByAvailableAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableAmount, opts...).ToFunc()
}

// ByFrozenAmount orders the results by the frozen_amount field.
func ByFrozenAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozenAmount, opts...).ToFunc()
}

// ByTotalEarned orders the results by the total_earned field.
func ByTotalEarned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalEarned, opts...).ToFunc()
}

// ByTotalTransferred orders the results by the total_transferred field.
func ByTotalTransferred(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTransferred, opts...).ToFunc()
}
