// Code generated by ent, DO NOT EDIT.

package sharedaccountwallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldUserID, v))
}

// PendingAmount applies equality check predicate on the "pending_amount" field. It's identical to PendingAmountEQ.
func PendingAmount(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldPendingAmount, v))
}

// AvailableAmount applies equality check predicate on the "available_amount" field. It's identical to AvailableAmountEQ.
func AvailableAmount(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldAvailableAmount, v))
}

// FrozenAmount applies equality check predicate on the "frozen_amount" field. It's identical to FrozenAmountEQ.
func FrozenAmount(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldFrozenAmount, v))
}

// TotalEarned applies equality check predicate on the "total_earned" field. It's identical to TotalEarnedEQ.
func TotalEarned(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldTotalEarned, v))
}

// TotalTransferred applies equality check predicate on the "total_transferred" field. It's identical to TotalTransferredEQ.
func TotalTransferred(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldTotalTransferred, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldUserID, v))
}

// PendingAmountEQ applies the EQ predicate on the "pending_amount" field.
func PendingAmountEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldPendingAmount, v))
}

// PendingAmountNEQ applies the NEQ predicate on the "pending_amount" field.
func PendingAmountNEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldPendingAmount, v))
}

// PendingAmountIn applies the In predicate on the "pending_amount" field.
func PendingAmountIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldPendingAmount, vs...))
}

// PendingAmountNotIn applies the NotIn predicate on the "pending_amount" field.
func PendingAmountNotIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldPendingAmount, vs...))
}

// PendingAmountGT applies the GT predicate on the "pending_amount" field.
func PendingAmountGT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldPendingAmount, v))
}

// PendingAmountGTE applies the GTE predicate on the "pending_amount" field.
func PendingAmountGTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldPendingAmount, v))
}

// PendingAmountLT applies the LT predicate on the "pending_amount" field.
func PendingAmountLT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldPendingAmount, v))
}

// PendingAmountLTE applies the LTE predicate on the "pending_amount" field.
func PendingAmountLTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldPendingAmount, v))
}

// AvailableAmountEQ applies the EQ predicate on the "available_amount" field.
func AvailableAmountEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldAvailableAmount, v))
}

// AvailableAmountNEQ applies the NEQ predicate on the "available_amount" field.
func AvailableAmountNEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldAvailableAmount, v))
}

// AvailableAmountIn applies the In predicate on the "available_amount" field.
func AvailableAmountIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldAvailableAmount, vs...))
}

// AvailableAmountNotIn applies the NotIn predicate on the "available_amount" field.
func AvailableAmountNotIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldAvailableAmount, vs...))
}

// AvailableAmountGT applies the GT predicate on the "available_amount" field.
func AvailableAmountGT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldAvailableAmount, v))
}

// AvailableAmountGTE applies the GTE predicate on the "available_amount" field.
func AvailableAmountGTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldAvailableAmount, v))
}

// AvailableAmountLT applies the LT predicate on the "available_amount" field.
func AvailableAmountLT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldAvailableAmount, v))
}

// AvailableAmountLTE applies the LTE predicate on the "available_amount" field.
func AvailableAmountLTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldAvailableAmount, v))
}

// FrozenAmountEQ applies the EQ predicate on the "frozen_amount" field.
func FrozenAmountEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldFrozenAmount, v))
}

// FrozenAmountNEQ applies the NEQ predicate on the "frozen_amount" field.
func FrozenAmountNEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldFrozenAmount, v))
}

// FrozenAmountIn applies the In predicate on the "frozen_amount" field.
func FrozenAmountIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldFrozenAmount, vs...))
}

// FrozenAmountNotIn applies the NotIn predicate on the "frozen_amount" field.
func FrozenAmountNotIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldFrozenAmount, vs...))
}

// FrozenAmountGT applies the GT predicate on the "frozen_amount" field.
func FrozenAmountGT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldFrozenAmount, v))
}

// FrozenAmountGTE applies the GTE predicate on the "frozen_amount" field.
func FrozenAmountGTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldFrozenAmount, v))
}

// FrozenAmountLT applies the LT predicate on the "frozen_amount" field.
func FrozenAmountLT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldFrozenAmount, v))
}

// FrozenAmountLTE applies the LTE predicate on the "frozen_amount" field.
func FrozenAmountLTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldFrozenAmount, v))
}

// TotalEarnedEQ applies the EQ predicate on the "total_earned" field.
func TotalEarnedEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldTotalEarned, v))
}

// TotalEarnedNEQ applies the NEQ predicate on the "total_earned" field.
func TotalEarnedNEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldTotalEarned, v))
}

// TotalEarnedIn applies the In predicate on the "total_earned" field.
func TotalEarnedIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldTotalEarned, vs...))
}

// TotalEarnedNotIn applies the NotIn predicate on the "total_earned" field.
func TotalEarnedNotIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldTotalEarned, vs...))
}

// TotalEarnedGT applies the GT predicate on the "total_earned" field.
func TotalEarnedGT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldTotalEarned, v))
}

// TotalEarnedGTE applies the GTE predicate on the "total_earned" field.
func TotalEarnedGTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldTotalEarned, v))
}

// TotalEarnedLT applies the LT predicate on the "total_earned" field.
func TotalEarnedLT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldTotalEarned, v))
}

// TotalEarnedLTE applies the LTE predicate on the "total_earned" field.
func TotalEarnedLTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldTotalEarned, v))
}

// TotalTransferredEQ applies the EQ predicate on the "total_transferred" field.
func TotalTransferredEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldEQ(FieldTotalTransferred, v))
}

// TotalTransferredNEQ applies the NEQ predicate on the "total_transferred" field.
func TotalTransferredNEQ(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNEQ(FieldTotalTransferred, v))
}

// TotalTransferredIn applies the In predicate on the "total_transferred" field.
func TotalTransferredIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldIn(FieldTotalTransferred, vs...))
}

// TotalTransferredNotIn applies the NotIn predicate on the "total_transferred" field.
func TotalTransferredNotIn(vs ...float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldNotIn(FieldTotalTransferred, vs...))
}

// TotalTransferredGT applies the GT predicate on the "total_transferred" field.
func TotalTransferredGT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGT(FieldTotalTransferred, v))
}

// TotalTransferredGTE applies the GTE predicate on the "total_transferred" field.
func TotalTransferredGTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldGTE(FieldTotalTransferred, v))
}

// TotalTransferredLT applies the LT predicate on the "total_transferred" field.
func TotalTransferredLT(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLT(FieldTotalTransferred, v))
}

// TotalTransferredLTE applies the LTE predicate on the "total_transferred" field.
func TotalTransferredLTE(v float64) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.FieldLTE(FieldTotalTransferred, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharedAccountWallet) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharedAccountWallet) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharedAccountWallet) predicate.SharedAccountWallet {
	return predicate.SharedAccountWallet(sql.NotPredicates(p))
}
